Мурзин Дмитрий
kontur-courses/fp pull request #117
Opened 2021-12-20 14:51 UTC by dmrz1n

@HolyPrapor

2021-12-20 18:35 UTC, HolyPrapor requested changes

2021-12-20 18:35 UTC, HolyPrapor commented on Homework/CLI/Client.cs
> +    public class Client : IClient
Общие замечания по клиенту:
1. Запуск без аргументов не пишет совсем ничего, приходится разбираться
2. `--help` выбрасывает эксепшн, кажется, что это не совсем правильное поведение :(
3. Аналогично с `--version`
4. Ничего не пишется при успешном окончании работы. Хотелось бы увидеть путь до сгенерированного файлика или хотя бы сообщение о том что всё ок

2021-12-20 18:35 UTC, HolyPrapor commented on Homework/CLI/Options.cs
> +    public class Options
Расскажи про этот класс: его подразумевалось использовать для многих клиентов?
Если так, то как бы ты реализовал `GUI` клиента, сильно бы он отличался от текущего? Появилось бы какое-то дублирование кода, если оставить всё так как есть?

2021-12-20 18:35 UTC, HolyPrapor commented on Homework/CLI/CommandLineHandlerConveyor.cs
> +    public class CommandLineHandlerConveyor : IHandlerConveyor
На мой вкус, имя `Conveyor` получилось сложным (манипулятор, кажется?)
Причем ничего умнее, чем хранение хэндлеров он не делает (и не манипулирует)

Может, подумаем в сторону переименования? (Речь и про интерфейс тоже)

2021-12-20 18:35 UTC, HolyPrapor commented on Homework/CLI/Program.cs
> +                painter.Draw(scope.Resolve<IUserConfig>().OutputFilePath);
Можно ли как-то избавиться от этого внешнего вызова `scope.Resolve<IUserConfig>()`?
А то у нас все взаимодействия скрыты, но тут почему-то он торчит

2021-12-20 18:35 UTC, HolyPrapor commented on Homework/CLI/Client.cs
> +        private readonly Dictionary<string, Func<string, string>> modifiers;
А точно этот словарь должен быть в клиенте?

2021-12-20 18:35 UTC, HolyPrapor commented on Homework/TagsCloudContainer/CloudLayouters/CircularCloudLayouter.cs
> +        private readonly List<Rectangle> _rectangles;
Хм
Где-то стиль приватных переменных с `_` в виде префикса, а где-то нет.
Выберем что-нибудь одно?

2021-12-20 18:35 UTC, HolyPrapor commented on Homework/TagsCloudContainer/CloudPainter.cs
> +                var savingName = pathToSaving + "\\tagcloud" + "." + config.ImageFormat;
Немного жалко, что я не могу повлиять на имя файла.
В одну папку только одно изображение за раз можно генерировать :(

2021-12-20 18:35 UTC, HolyPrapor commented on Homework/TagsCloudContainer/TextParsers/ISourceReader.cs
> +
```suggestion
```

Лишняя строчка, форматирование поехало)

2021-12-20 18:38 UTC, HolyPrapor commented
И ещё общий вопрос: много публичных классов, они действительно все нужны публичные? Что если кто-то подключит библиотеку извне, без клиента?

2021-12-20 18:56 UTC, dmrz1n commented on Homework/CLI/Client.cs
> +    public class Client : IClient
Ага, понял. Вообще, про поведение с --help и --version я то ли в оффдоке читал, то ли на stackoverflow, уже не помню. Но мне тоже казалось странным, оставлял, пока не было замечаний. Исправим.

2021-12-20 20:55 UTC, dmrz1n commented on Homework/CLI/Options.cs
> +    public class Options
Вообще, Options это, как я понял, стандартное название для класса, в который складывает обработанные аргументы командной строки CommandLineParser, поэтому его поля размечены атрибутами. Я не знал, как принято в таком случае именовать класс - то ли оставлять, как в доке библиотеки (чтобы меня поняли, если она распространенная), то ли придумывать название, подходящее для моего проекта.

Подразумевалось, что IUserConfig будет как бы переходником к разным клиентам. В случае консольного клиента мы в классе Client переводим Options в CommandLineConfig, который является реализацией IUserConfig с помощью метода GetConfigResult.

Насчет GUI - думаю, это зависит от того, какие дополнительные фичи потребуются от графического интерфейса, но вообще, кажется, что не должно доставить проблем что-то добавить в иную реализацию IUserConfig. Например, предыдущий наставник предложил добавить массив Tags для графического интерфейса - мол, вдруг пользователь захочет использовать не файловый ввод, а просто вручную ввести сколько-то слов. Мне понравилась идея, и я решил сделать такую возможность и для консольного клиента. Идея в том, чтобы просто добавить поле для приема какого-то вида данных в реализацию интерфейса.

2021-12-21 05:43 UTC, HolyPrapor commented on Homework/CLI/Options.cs
> +    public class Options
Да я бы не сказал, что какое-то стандартное

Не стоит от каждого пользователя ожидать, что он знаком с конкретной библиотекой

Но я тебя понял, окей

2021-12-21 13:23 UTC, dmrz1n commented on Homework/CLI/CommandLineHandlerConveyor.cs
> +    public class CommandLineHandlerConveyor : IHandlerConveyor
Подразумевалось, что это конвейер :) Но, действительно, если проводить аналогию с реальным миром конвейер подразумевает обработку, а не только набор автоматов, которые на этом конвейере работают. Может тогда IHandlersStorage?
Думаю, в обоих классах, название которых содержит CommandLine можно поставить просто Console.
В итоге получим ConsoleConfig, ConsoleHandlersStorage и IHandlersStore, уже покороче и поприятнее. 

Вообще, проблема родом из архитектуры, под пунктом 2 обсуждения в телеге. Если бы здесь была функциональность обработки, можно было бы и BoringWords сюда спрятать и словарь из Client перенести.

2021-12-21 13:25 UTC, dmrz1n commented on Homework/CLI/Program.cs
> +                painter.Draw(scope.Resolve<IUserConfig>().OutputFilePath);
Добавлю в конструктор CloudPainter'а строку пути сохранения, будем ее формировать из переданного пути и опции имени файла, которую собираюсь добавить.

2021-12-21 13:26 UTC, dmrz1n commented on Homework/CLI/Client.cs
> +        private readonly Dictionary<string, Func<string, string>> modifiers;
Думаю спрятать его в виде приватного статика в IHandlersStorage. Кстати, все возможные обработчики должны распространяться на все возможные клиенты - может, интерфейс не нужен в этом случае?

2021-12-21 13:29 UTC, dmrz1n commented on Homework/TagsCloudContainer/CloudLayouters/CircularCloudLayouter.cs
> +        private readonly List<Rectangle> _rectangles;
Ага, тут трабла в том, что код из разных задач -  один наставник сказал следовать советам решарпера, если нет причин не следовать, другой сказал, что в шарпе не принято с подчерков начинать названия приватных переменных :) Приведу к одному стилю.

2021-12-21 13:57 UTC, HolyPrapor commented on Homework/CLI/Client.cs
> +        private readonly Dictionary<string, Func<string, string>> modifiers;
Интерфейс чего, вопрос не очень понял

Но утверждение у тебя верное

2021-12-21 13:59 UTC, HolyPrapor commented on Homework/TagsCloudContainer/CloudLayouters/CircularCloudLayouter.cs
> +        private readonly List<Rectangle> _rectangles;
> другой сказал, что в шарпе не принято с подчерков начинать названия приватных переменных :)
Зависит от команды, но в 99% случаев да, подчеркиваний нет)

Мне без разницы какой ты выберешь стиль, но кажется проще в этом классе их убрать просто

2021-12-21 14:10 UTC, dmrz1n commented on Homework/CLI/Client.cs
> +        private readonly Dictionary<string, Func<string, string>> modifiers;
Уточню - сейчас есть интерфейс IHandlerConveyor, хочу его убрать и сделать класс HandlersStorage, в котором будут инкапсулированы доступные хэндлеры. Ему в конструктор будет передаваться набор строк (заданных юзером хэндлеров) и конструктор будет заполнять два списка - в один он положит функции обработки строк (распознанные хэндлеры), в другой названия нераспознанных хэндлеров. Как-то так.

2021-12-21 14:42 UTC, HolyPrapor commented on Homework/CLI/Client.cs
> +        private readonly Dictionary<string, Func<string, string>> modifiers;
Понял

Можешь так, да)

2021-12-23 05:52 UTC, HolyPrapor approved these changes

2021-12-23 05:52 UTC, HolyPrapor commented on Homework/ContainerConfigurers/AutofacConfigurer.cs
> +            return c.Resolve<IUserConfig>().OutputFilePath +
`Path.Combine`, чтобы хорошо пережить переход на `Linux`, например :)

2022-11-01 05:49 UTC, closed without merging