Иван Малямов
kontur-courses/fp pull request #120
Opened 2021-12-22 16:32 UTC by ivanarray

review: @hariton27sy
task: #TagCloudResult

2021-12-23 20:05 UTC, hariton27sy requested changes
Не знаю, говорил ли тебе что-нибудь прошлый наставник, но мне не нравится, что ты осмысленно много раз вызываешь Resolve из контейнера, тем самым тут появляется паттерн serviceDiscovery а это ну такой спорный паттерн проектирования. По хорошему возможно стоит выделить отдельную сущность, которая получала бы все необходимое через параметры конструктора, и в main остался бы один единственный TryResolve который бы резолвил точку входа в приложение. 

Не вижу тестов которые бы проверяли Result.False сценарии, что нет эксепшенов при некорректных условиях, что GatValueOrThrow упадет если Result.False

2021-12-23 20:05 UTC, hariton27sy commented on TagsCloudContainerHomeWork/TagsCloudContainerCore/CircularLayouter/CircularCloudLayoutParameters.cs
> +        if (Radius > MaxRadius)
Здесь еще остался Exception который по стеку поднимется до конца

2021-12-23 20:05 UTC, hariton27sy commented on TagsCloudContainerHomeWork/TagsCloudContainerCore/Result/Result.cs
> +        throw new InvalidOperationException($"No value. Only Error {Error}");
Интересное сообщение конечно)

2021-12-23 20:05 UTC, hariton27sy commented on TagsCloudContainerHomeWork/TagsCloudContainerCore/StatisticMaker/TagStatisticMaker.cs
> +        return orderedPairs[1];
Не вывалится Exception если не будет элементов? А почему первый а не нулевой?

2021-12-23 20:05 UTC, hariton27sy commented on TagsCloudContainerHomeWork/TagsCloudContainerCore/StatisticMaker/TagStatisticMaker.cs
> +        return orderedPairs[^1];
Аналогично

2021-12-24 07:56 UTC, ivanarray commented on TagsCloudContainerHomeWork/TagsCloudContainerCore/StatisticMaker/TagStatisticMaker.cs
> +        return orderedPairs[1];
Действительно нулевой, мой недочет

2022-11-01 05:49 UTC, closed without merging