Алемасцев Никита
kontur-courses/fp pull request #121
Opened 2021-12-22 16:55 UTC by nikovOne

@LevShisterov

2021-12-22 21:40 UTC, LevShisterov requested changes

2021-12-22 21:40 UTC, LevShisterov commented on ConsoleClient/Program.cs
> +            image.GetValueOrThrow().Save("Sample.png");
Куда тут полетит исключение?

2021-12-22 21:40 UTC, LevShisterov commented on ConsoleClient/Program.cs
> +﻿#region
Не сталкивался чтобы блок включений обрамляли в регион. Можешь подсказать зачем?

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/CircularCloudLayouter.cs
> +            return new Result<Rectangle[]>(null, rectangles.ToArray());
А как же ```Result.Ok``` или даже ```implicit operator Result<T>(T v)```?

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/CircularCloudLayouter.cs
> +                PutNextRectangle(graphics.MeasureString(word, font).ToSize()).GetValueOrThrow());
Куда полетит исключение от ```.GetValueOrThrow()```?

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/CircularCloudLayouter.cs
> +                    $"Size is empty! Width: {rectangleSize.Width}, height: {rectangleSize.Height}");
```suggestion
                    $"Width and height should be greater than zero. Width: {rectangleSize.Width}, height: {rectangleSize.Height}");
```

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/Extensions/DictionaryExtensions.cs
> +                dictionary[key] = func.Compile().Invoke(key);
Немного странно что для обновления ты передаешь наружу ключ, а не текущее значение. В итоге в месте вызова тебе приходится писать ```freqDictionary[word]```.

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/FileReader.cs
> +            var reader = new StreamReader(path);
А тут может упасть?

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/FileReader.cs
> +                foreach (var word in line.Split(separators).Where(word => word.Length > 0))
У ```.Split``` есть параметр ```StringSplitOptions.RemoveEmptyEntries```.

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/FileReader.cs
> +            var line = reader.ReadLine();
А тут может упасть?

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/FileReader.cs
> +            reader.Close();
Есть специальный паттерн с использованием `using`.

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/FileReader.cs
> +    public class FileReader : IFileReader
Это ведь, по сути, читатель `.txt` файлов? Наверное стоило отразить это в названии класса. Иначе потом будет сложно добавить чтение `.doc` файлов.

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/ImageGenerator.cs
> +            return image == null
Проверку этого надо было делать в конструкторе. Раньше упадешь - меньше бесполезной работы будет проделано.

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/ImageGenerator.cs
> +            var brush = Graphics.FromImage(image);
Название переменной не соответствует типу. Может вводить в заблуждение.

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/Interfaces/ICloudLayouter.cs
> +        Result<IEnumerable<Rectangle>> PutWords(IEnumerable<string> words, Font font, Graphics graphics);
Это какие-то точки расширения на будущее?

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/Interfaces/IImageGenerator.cs
> +        Result<Font> GetFont();
Не используется.

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/Interfaces/ITagCloudCreator.cs
> +        Result<Bitmap> CreateAndSaveCloudFromTextFile(string inputPath);
Кажется название метода немного запутывает. Существующий вариант реализации интерфейса просто рисует на  битмапе.

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/TagCloudCreator.cs
> +        }
Кажется это не имеет никакого отношения к классу в котором оно находится. И см. коммент в точке вызова.

2021-12-22 21:40 UTC, LevShisterov commented on ConsoleClient/Program.cs
> +            builder.RegisterAssemblyTypes(assemblyInfo)
```suggestion
            builder.RegisterAssemblyTypes(typeof(TagCloudCreator).Assembly)
```

2021-12-22 21:40 UTC, LevShisterov commented on ConsoleClient/Program.cs
> +            var graphics = Graphics.FromImage(bitmap);
Это IDisposable - надо диспозить. То же касается шрифтов, брашей, и прочих GDI объектов.

2021-12-22 21:40 UTC, LevShisterov commented on TagsCloudVisualization/TagsCloudVisualization.csproj
> +        <Nullable>enable</Nullable>
Из-за этой настройки у тебя все null подсвечиваются. Попробуй почитать про неё.

2021-12-23 07:31 UTC, nikovOne commented on ConsoleClient/Program.cs
> +﻿#region
Райдер так делает, когда я использую Reformat and CleanUp

2021-12-23 08:37 UTC, LevShisterov commented on ConsoleClient/Program.cs
> +﻿#region
Ага. Тогда имеет смысл поискать и отключить эту опцию. Хотя бы в чисто ознакомительных целях.

2021-12-26 05:57 UTC, nikovOne commented on TagsCloudVisualization/Interfaces/ICloudLayouter.cs
> +        Result<IEnumerable<Rectangle>> PutWords(IEnumerable<string> words, Font font, Graphics graphics);
Я их и использую. Чтобы можно было передавать слово и он делал из него прямоугольник. Это лишнее в интерфейсе?

2021-12-26 09:20 UTC, LevShisterov commented on ConsoleClient/Program.cs
> +            image.GetValueOrThrow().Save("Sample.png");
Тут я имел в виду исключения из ```GetValueOrThrow()``` и ```.Save("Sample.png")```. Не принято исключения просто из программы наружу выкидывать.

2021-12-26 09:44 UTC, LevShisterov requested changes

2021-12-26 09:44 UTC, LevShisterov commented on ConwaysGameOfLife/Program.cs
> +﻿#region
Тут какой-то левый файл поменялся.

2021-12-26 09:44 UTC, LevShisterov commented on TagsCloudVisualization/CircularCloudLayouter.cs
> +            return Result.Ok(center);
А можно прямо ```return center;```

2021-12-26 09:52 UTC, LevShisterov requested changes

2021-12-26 09:52 UTC, LevShisterov commented on TagsCloudVisualization/CircularCloudLayouter.cs
> +                : Result.Fail<Rectangle>(rectangleResult.Error);
А как же ```.Then```?

2021-12-26 14:04 UTC, LevShisterov commented on TagsCloudVisualization/ImageGenerator.cs
> +            var graphics = Graphics.FromImage(image);
IDisposable

2021-12-26 15:27 UTC, LevShisterov commented on TagsCloudVisualization/CircularCloudLayouter.cs
> +        }
Метод только для тестов.

2021-12-26 15:52 UTC, LevShisterov commented on TagsCloudVisualization/WordPreparator.cs
> +            var words = morphAnalyzer.Parse(unpreparedWords).ToArray();
Могу предположить, что мы не знаем может внешний код выкинуть исключение или нет, имеет смысл обернуть в `.Of`.

2021-12-26 19:48 UTC, LevShisterov approved these changes

2022-11-01 05:49 UTC, closed without merging