Карасев Артемий
kontur-courses/fp pull request #129
Opened 2022-12-17 09:53 UTC by Rizhiy825

Привет, @Danko19 !
Я закончил работу над приложением, ошибки обрабатываются теперь с помощью класса Result. Очень жду обратку)

2022-12-18 09:03 UTC, Danko19 requested changes

2022-12-18 09:03 UTC, Danko19 commented on TagsCloud/Result.cs
> +    public struct Result<T>
Почему решил сделать структурой?

2022-12-18 09:03 UTC, Danko19 commented on TagsCloud/Result.cs
> +        public Result(string error, T value = default(T))
Если объединить с классом Result, то конструктор можно будет сделать приватным и создавать всегда через `Result.`

2022-12-18 09:03 UTC, Danko19 commented on TagsCloud/TagCloud.cs
> +            var validResult = fileValidator.VerifyFileExistence(textFilePath);
Валидацию наличия файла хочется делать в рядом с его чтением, желательно в одной цепочке вызовов через `Then`

2022-12-18 09:03 UTC, Danko19 commented on TagsCloud/TextWorkers/MorphsParser.cs
> +            var morphInfo = morph.Parse(words);
Не обрабатываем потенциальную ошибку во внешней библиотеке

2022-12-18 09:04 UTC, Danko19 commented
Не хватает тестов на модули, работающих с Result<T>, с проверкой Result.Ok() и Result.Fail()

2022-12-18 09:12 UTC, Danko19 commented
Словил Exception, входные данные - [text2.txt](https://github.com/kontur-courses/fp/files/10253495/text2.txt)
![image](https://user-images.githubusercontent.com/37505721/208290119-53743e9c-5e55-474e-9988-507b61b54b70.png)

2022-12-19 07:51 UTC, Rizhiy825 commented on TagsCloud/Result.cs
> +    public struct Result<T>
В файлах, которые я нашел в проекте, этот тип выполнен в виде структуры. Решил просто не трогать его и использовать "как есть". Согласен, можно объединить с Result

2022-12-20 18:15 UTC, Danko19 requested changes

2022-12-20 18:15 UTC, Danko19 commented on TagsCloud/TextWorkers/MorphsParser.cs
> +            var morph = new MorphAnalyzer(true);
Лишнее :)

2022-12-20 18:15 UTC, Danko19 commented on TagsCloud/Validators/MorphsValidator.cs
> +            var morphInfo = morphParser.Parse(words);
Все ещё никак не отлавливаем потенциальный Exception в библиотеке

2022-12-20 18:15 UTC, Danko19 commented on TagsCloud/Validators/ClientValidator.cs
> +        public char[] ValidChars { get; private set; }
Предлагаю сделать HashSet-ом, чтобы Contains в `ValidateRussianInput` работал за константу

2022-12-20 18:15 UTC, Danko19 commented on TagsCloudTests/ValidatorsShould/BitmapValidatorShould.cs
> +            validator = new BitmapValidator();
`BitmapValidator` не хранит состояние, не обязательно пересоздавать его для каждого теста в SetUp-е

2022-12-20 18:15 UTC, Danko19 commented on TagsCloudTests/ValidatorsShould/BitmapValidatorShould.cs
> +            validator = new BitmapValidator();
В остальных тестах аналогично

2023-11-23 04:58 UTC, closed without merging