Вашурин Артем
kontur-courses/fp pull request #132
Opened 2022-12-19 13:19 UTC by ArtAkaArt

@desolver

2022-12-22 18:22 UTC, desolver requested changes

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainerTests/WordSizeCalculatorTests.cs
> +[TestFixture]
`[TestFixture]`  можно не писать, если в классе есть методы, помеченные атрибутом `[Test]`

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainerTests/CloudDrawerTests.cs
> +        });
Этот набор опций один-в-один как в тесте ниже, давай вынесем в какой-нибудь метод

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainer/WordsFilter.cs
> +                .Insert(1, x))
Если я правильно понимаю то, что написано в этой строчке - ты в первый индекс вставляешь x, а почему это не сделать проще через интерполяцию?

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainer/WordsFilter.cs
> +            "^(\\w+){((?!).)*$".Insert(11, jointPos);
Аналогично тут

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainer/WordsFilter.cs
> +        jointPos = jointPos.Length == 0 ? "= (,|=)" : jointPos;
Набор этих символов очень похож на шаблон, в который вставляется символ в 1 индекс, только в этом случае символом стал пробел. Давай может быть и сделаем из него шаблон, чтобы, меняя его в одном месте, не забыть поменять в другом?

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainer/WordsFilter.cs
> +            : new Result<List<string>>(inputWords.Where(x => !boringWords.Contains(x)).ToList());
Получилось небольшое дублирование кода тут, два раза создаешь один и тот же объект Result. Видно, что отличаются они именно значением, которое передается внутрь. Обычно в таких случаях выше создается переменная, в которую и присваивается зависящее от условия значение, и уже оно прокидывается в единственный Result

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainer/WordsFilter.cs
> +        // something like that ^(\w+){((?!=SPRO(,|=)|=PR(,|=)|=PART(,|=)|=CONJ(,|=)).)*$
Какие-то забытые комменты?

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainer/BudgetDocParser.cs
> +        var parser = new Parser(filePath);
`Parser` реализует `IDisposable`

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainer/CloudDrawer.cs
> +    public Result<string> DrawCloud(string path, Result<ICustomOptions> options)
А зачем принимать в методе `Result<T>`, если внутри ты используешь только его значение? Получается, что передаешь ненужную инфу (нарушается принцип ICP). Прокидывай просто `ICustomOptions` (к методу ниже это тоже относится)

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainer/CloudDrawer.cs
> +        var graphics = Graphics.FromImage(picture);
Забыл освободить ресурсы

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainer/CloudDrawer.cs
> +        var fontColor = new SolidBrush(Color.FromName(options.Value.FontColor));
И тут

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainer/CloudDrawer.cs
> +            "wmf" => new Result<ImageFormat>(ImageFormat.Wmf),
Дублируешь форматы из класса `CustomOptionsValidator`

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainer/CloudDrawer.cs
> +public class CloudDrawer
Обычно классы, которые внутри для инициализации принимают интерфейсы сами тоже реализуются какой-то интерфейс, чтобы и их можно было передать в другой класс

2022-12-22 18:22 UTC, desolver commented on CircularLayout/SpiralDrawer.cs
> +            var result = new List<PointF>();
Тут скрылась проблемка производительности, нужно ли нам размечать миллиард (условно) точек, если мы хотим разместить 3 прямоугольника?
Можно ли оптимизировать это место так, чтобы отдавать ровно столько прямоугольников, сколько нужно вызывающей программе?

2022-12-22 18:22 UTC, desolver commented on CircularLayout/CircularCloudLayout.cs
> +        public readonly int radius;
Публичные поля с большой буквы

2022-12-22 18:22 UTC, desolver commented on Result/Result.cs
> +public class Result<T>
Есть вопросики и предложения по поводу этого класса

1. Я не нашел ни одного места, где из экспешена бралось бы что-то кроме `Message`, так зачем прокидывать здоровенный экспешн, если из него нам нужно только сообщение?
2. Каст Result в bool в 9 строке вышел довольно неочевидным, отчасти из-за того, что названия переменных вида `resultDictionary`,  `wordsToDraw` (взял ближайшие найденные) почти правильные для типа `Result` (правильнее было бы скорее `dictionaryResult` и `wordsToDrawResult`), но они ни в текущем виде ни в предложенном мной не соответствуют конвентам именования булевых переменных (я про всякие is, has, exists, contains и тд)
3. Не устал везде писать `new Result<...>(...)`?😀 Для упрощения вызова таких штук обычно делают статические фабричные методы, у которых более короткий синтаксис вызова (см. 4 пункт)
4. Самый важный пункт, который освободит тебя от того, чтобы править первые три)) А зачем писать свои велосипеды. если все написано за тебя? Result из соседнего проекта уже готов ко всему, если не нравится он, а хочешь заиспользовать что-то более популярное и широко используемое, можешь поставить `FluentResults` и перевести все на них

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainer/Program.cs
> +        var drawer = ActivatorUtilities.CreateInstance<CloudDrawer>(container);
Тут можно проще, ты ведь сложил зависимости в контейнер, значит он должен уметь их тебе возвращать и создавать, проверь, какие методы у него есть и замени это выражение них)

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainer/FileToDictionaryConverter.cs
> +        var taggedWords = process.StandardOutput
Кажется, после этого места ниже процесс тебе уже не нужен?

2022-12-22 18:22 UTC, desolver commented on TagsCloudContainer/CustomOptionsValidator.cs
> +            return new Result<ICustomOptions>(new ArgumentException("Texts directory does not exist"));
В задании сказано не только кинуть сообщение об ошибке, но и сделать так, чтобы пользователю было понятно, что ему нужно сделать, чтобы исправить ситуацию. Увидев сообщение "Директория с текстами не найдена", я бы понятия не имел, куда мне нужно сходить, чтобы её создать))
Аналогично со всеми другими сообщениями в проекте

2022-12-22 18:29 UTC, ArtAkaArt commented on TagsCloudContainer/WordsFilter.cs
> +        // something like that ^(\w+){((?!=SPRO(,|=)|=PR(,|=)|=PART(,|=)|=CONJ(,|=)).)*$
Нет, оставил для наглядности, что должно получаться на выходе :)

2022-12-25 13:07 UTC, desolver commented on TagsCloudContainer/CloudDrawer.cs
> +            return resultDictionary.Error.AsResult();
А тут равзе вернется не положительный Result? Кажется, вызывающая программа будет считать, что все хорошо, и так же с ошибками ниже. Или так и задумано?

2022-12-25 13:07 UTC, desolver commented on TagsCloudContainer/Program.cs
> +        Console.WriteLine(result.IsSuccess? result.GetValueOrThrow():result.Error);
Что-то случилось с отступами)

2022-12-25 13:07 UTC, desolver commented on TagsCloudContainer/WordsFilter.cs
> +        inputWords = boringWords is null ? inputWords : inputWords.Where(x => !boringWords.Contains(x)).ToList();
Сложные тернарники лучше писать так:
```
inputWords = boringWords is null
    ? inputWords
    : inputWords.Where(x => !boringWords.Contains(x)).ToList();
```

2022-12-25 13:11 UTC, desolver commented on CircularLayout/CircularCloudLayout.cs
> +            return (false, rectangle).AsResult();
`AsResult` если я не ошибаюсь возвращает успешный результат, он тут точно нужен? Проверь на всякий по коду, где ещё такие ситуации есть

2023-11-23 04:58 UTC, closed without merging