Соцук Виктор
kontur-courses/fp pull request #146
Opened 2022-12-23 16:14 UTC by viksot

Hi, @Leoltron!
Homework is done. Please, check

2022-12-25 18:28 UTC, Leoltron requested changes
В целом, мне нравится, но надо доработать

2022-12-25 18:28 UTC, Leoltron commented on TagCloudUnitTests/TxtFileReaderTests.cs.cs
> +        public void ReadAllText_ReturnsAllFileText_WhenFileExists()
Этот тест (и аналогичный для .docx) не проходит у меня, файл не находит. Пытается достать файл из `TagCloudUnitTests\bin\Debug\net48\TestTextFiles\TestText.txt`

2022-12-25 18:28 UTC, Leoltron commented on TagCloud/CloudLayouter/CircularCloudLayouter.cs
> +                throw new ArgumentException("width and height of rectangle must be more than zero");
В задании написано "Вместо исключений всюду в программе используй паттерн Result<T>"

2022-12-25 18:28 UTC, Leoltron commented on TagCloud/FileReader/DocxFileReader.cs
> +                return Result.Fail<string>($"File {filePath} has invalid format");
Почему бы не описать, о каком формате идет речь?

2022-12-25 18:28 UTC, Leoltron commented on TagCloud/FileReader/DocxFileReader.cs
> +                    WordprocessingDocument.Open(filePath, false))
А если это просто произвольный файл с .doc в конце имени? Давай такие случаи тоже обрабатывать

2022-12-25 18:28 UTC, Leoltron commented on TagCloud/FileReader/DocxFileReader.cs
> +                wordDocument.Close();
Лишнее закрытие, в конце using-а вызовется Dispose, который выполняет ту же функцию

2022-12-25 18:28 UTC, Leoltron commented on TagCloud/AppConfiguration/ConsoleAppConfigProvider.cs
> +                return Result.Fail<Options>($"Input file {options.InputFileFullPath} has invalid format");
Почему бы не сказать явно, какие форматы поддерживает программа?

2022-12-25 18:28 UTC, Leoltron commented on TagCloud/AppConfiguration/ConsoleAppConfigProvider.cs
> +                return Result.Fail<Options>($"Output file {options.OutputImageFullPath} has invalid format");
Почему бы не сказать явно, какие форматы поддерживает программа?

2022-12-25 18:28 UTC, Leoltron commented on TagCloud/AppConfiguration/ConsoleAppConfigProvider.cs
> +                return Result.Fail<Options>($"Cloud form {options.CloudForm} isn't supported");
Поддерживаемые формы облака не описаны в сообщении

2022-12-25 18:28 UTC, Leoltron commented on TagCloud/AppConfiguration/ConsoleAppConfigProvider.cs
> +                return Result.Fail<Options>($"Image size {options.ImageWidth} x {options.ImageHeight} is invalid");
Можем быть и поточнее, invalid слишком обще

2022-12-25 18:28 UTC, Leoltron commented on TagCloud/AppConfiguration/ConsoleAppConfigProvider.cs
> +                return Result.Fail<Options>($"Font min size {options.MinFontSize} is invalid");
Можем быть и поточнее, invalid слишком обще

2022-12-25 18:28 UTC, Leoltron commented on TagCloud/AppConfiguration/ConsoleAppConfigProvider.cs
> +                return Result.Fail<Options>($"Font max size {options.MaxFontSize} is invalid");
Мы же знаем, что MaxFontSize должен быть положительным, так давай так и скажем вместо "invalid"

2022-12-25 18:28 UTC, Leoltron commented on TagCloud/AppConfiguration/ConsoleAppConfigProvider.cs
> +                return Result.Fail<Options>($"Word coloring {options.WordColoring} isn't supported");
Поддерживаемые формы раскраски не описаны в сообщении

2022-12-26 08:46 UTC, viksot commented on TagCloud/FileReader/DocxFileReader.cs
> +                return Result.Fail<string>($"File {filePath} has invalid format");
\+

2022-12-26 08:47 UTC, viksot commented on TagCloud/FileReader/DocxFileReader.cs
> +                wordDocument.Close();
\+

2022-12-26 08:57 UTC, viksot commented on TagCloud/AppConfiguration/ConsoleAppConfigProvider.cs
> +                return Result.Fail<Options>($"Input file {options.InputFileFullPath} has invalid format");
\+

2022-12-26 09:04 UTC, viksot commented on TagCloud/AppConfiguration/ConsoleAppConfigProvider.cs
> +                return Result.Fail<Options>($"Output file {options.OutputImageFullPath} has invalid format");
\+

2022-12-26 09:15 UTC, viksot commented on TagCloud/AppConfiguration/ConsoleAppConfigProvider.cs
> +                return Result.Fail<Options>($"Cloud form {options.CloudForm} isn't supported");
\+

2022-12-26 09:24 UTC, viksot commented on TagCloud/AppConfiguration/ConsoleAppConfigProvider.cs
> +                return Result.Fail<Options>($"Image size {options.ImageWidth} x {options.ImageHeight} is invalid");
\+

2022-12-26 09:33 UTC, viksot commented on TagCloud/AppConfiguration/ConsoleAppConfigProvider.cs
> +                return Result.Fail<Options>($"Font min size {options.MinFontSize} is invalid");
\+

2022-12-26 09:33 UTC, viksot commented on TagCloud/AppConfiguration/ConsoleAppConfigProvider.cs
> +                return Result.Fail<Options>($"Font max size {options.MaxFontSize} is invalid");
\+

2022-12-26 09:33 UTC, viksot commented on TagCloud/AppConfiguration/ConsoleAppConfigProvider.cs
> +                return Result.Fail<Options>($"Word coloring {options.WordColoring} isn't supported");
\+

2022-12-26 11:04 UTC, viksot commented on TagCloudUnitTests/TxtFileReaderTests.cs.cs
> +        public void ReadAllText_ReturnsAllFileText_WhenFileExists()
\+

2022-12-26 11:33 UTC, viksot commented on TagCloud/CloudLayouter/CircularCloudLayouter.cs
> +                throw new ArgumentException("width and height of rectangle must be more than zero");
\+

2022-12-26 11:45 UTC, viksot commented on TagCloud/FileReader/DocxFileReader.cs
> +                    WordprocessingDocument.Open(filePath, false))
Заменил Path.GetExtension() на string.EndsWith()

![image](https://user-images.githubusercontent.com/106755507/209544940-aeec9e3f-6d1c-43a7-83b3-21a1b21d1f20.png)

![image](https://user-images.githubusercontent.com/106755507/209545318-5741c7f1-7c83-4db9-96a4-373a41b3f057.png)

2022-12-26 12:56 UTC, Leoltron commented on TagCloudUnitTests/DocxFileReaderTests.cs
> +        private readonly string solutionDirectory = new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory).Parent.Parent.Parent.Parent.FullName;
Если ты научишься копировать тестовые текстовые документы в ту же директорию, тебе не придется строить такие жуткие пути

2022-12-26 12:56 UTC, Leoltron commented on TagCloud/TagCloud.csproj
> +    <Compile Include="ImageProcessing\OutputFileFormats.cs" />
А к чему эти `<Compile Include`-ы?

2022-12-26 12:56 UTC, Leoltron commented on TagCloud/FileReader/DocxFileReader.cs
> +                    WordprocessingDocument.Open(filePath, false))
Это не то, что я имел в виду. возьми какой-нибудь не-текстовый файл, добавь расширение .docx, и пропусти его через программу.

2022-12-26 14:34 UTC, viksot commented on TagCloud/FileReader/DocxFileReader.cs
> +                    WordprocessingDocument.Open(filePath, false))
Если это нетекстовый файл с расширением .docx, то метод File.Exists() выдаст false:

![image](https://user-images.githubusercontent.com/106755507/209559169-ff1856bd-75b8-4a04-afc0-c271eff83ffa.png)


Если файл word-овский, то всё ок:

![image](https://user-images.githubusercontent.com/106755507/209558771-61f6294b-4a6e-44a1-9389-d5e770257cb1.png)

То есть битый файл не пройдёт

2022-12-26 15:03 UTC, viksot commented on TagCloud/FileReader/DocxFileReader.cs
> +                    WordprocessingDocument.Open(filePath, false))
\+

2022-12-27 08:35 UTC, viksot commented on TagCloudUnitTests/DocxFileReaderTests.cs
> +        private readonly string solutionDirectory = new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory).Parent.Parent.Parent.Parent.FullName;
Не очень понял как это сделать. Сделал по-другому через вспомогательный класс DirectoryHandler.cs

2022-12-27 17:24 UTC, Leoltron approved these changes

2022-12-27 17:24 UTC, closed without merging