Шихов Роман
kontur-courses/fp pull request #152
Opened 2022-12-26 07:54 UTC by Hrenaki

Наставник: @Danko19

2022-12-26 18:27 UTC, Danko19 requested changes

2022-12-26 18:27 UTC, Danko19 commented on TagsCloudContainer/Infrastructure/WordLayoutBuilders/CircularWordLayoutBuilder.cs
> +                throw new ArgumentException("Size can't be empty");
В условиях задания:
>Вместо исключений всюду в программе используй паттерн Result<T>

Но тут ещё осталось исключение

2022-12-26 18:27 UTC, Danko19 commented on TagsCloudContainer/Infrastructure/WordPreparers/WordPreparer.cs
> +            if (words is null)
Проверка кажется лишней, получается что дважды проверяем `words` на null, тут и в `OkIf`

2022-12-26 18:27 UTC, Danko19 commented on TagsCloudContainer/Infrastructure/TagsCloudGenerator.cs
> +                                             .OnSuccess(r =>
Необычное форматирование, ещё не встречал такого. Если ты в райдере, то можно сдлеать клинап файла хоткеем `Ctrl + Alt + L`

2022-12-26 18:28 UTC, Danko19 commented
Хочется ещё тестов на `WordLinearColorProvider` и `WordLinearSizeProvider`

2022-12-27 08:41 UTC, Hrenaki commented on TagsCloudContainer/Infrastructure/WordLayoutBuilders/CircularWordLayoutBuilder.cs
> +                throw new ArgumentException("Size can't be empty");
Тут не получится сделать возращение результата, т.к. метод AddWord(...) уже возвращает экземпляр другого типа.
Плюс считаю, что если в эту функцию попадает нулевой размер(size), то это очень исключительная ситуация, при возникновении которой процесс генерации облака тегов должен быть остановлен

2022-12-27 14:01 UTC, Danko19 commented on TagsCloudContainer/Infrastructure/WordLayoutBuilders/CircularWordLayoutBuilder.cs
> +                throw new ArgumentException("Size can't be empty");
1. Кажется это не проблема. В боевом коде возвращаемое значение не используется, можно переделать его на `void`, т.е. `Result`
2. Соглашусь, в реальном проекте можно было бы так поступить. Но в учебных целях предлагаю всё таки сделать как предлагает задание

2023-11-23 04:58 UTC, closed without merging