Шмаков Данил
kontur-courses/fp pull request #162
Opened 2024-02-01 14:09 UTC by Reltig

@69raccoon96

2024-02-02 22:35 UTC, 69raccoon96 requested changes

2024-02-02 22:35 UTC, 69raccoon96 commented on TagCloudTests/ColorConverterTests.cs
> +        throw new Exception();
Should().BeTrue() наверное

2024-02-02 22:35 UTC, 69raccoon96 commented on TagCloud/Result.cs
> +        internal T Value { get; }
Хм, а зачем сделан внутренним? 
Видимо ожидается, что в других проектах будет использоваться метод ниже, тогда логичнее было бы сделать его вызов и тут, что-то типа
`public T Value => GetValueOrThrow();`

2024-02-02 22:35 UTC, 69raccoon96 commented on TagCloud/Result.cs
> +        internal T Value { get; }
Тогда получится сохранить удобство и избежать ситуаций, когда ты внутри проекта можешь попытаться получить значения, когда его нет

2024-02-02 22:35 UTC, 69raccoon96 commented on TagCloud/Result.cs
> +        internal T Value { get; }
Угу, понял почему так получилось, там пример дается с таким кодом, ну.. Кажется все равно нужно поправить

2024-02-02 22:45 UTC, 69raccoon96 requested changes

2024-02-02 22:45 UTC, 69raccoon96 commented on TagCloud/TagCloudServicesFactory.cs
> +                filter: provider.GetService<IWordFilter>()
А если файла не найден?

2024-02-02 22:45 UTC, 69raccoon96 commented on TagCloudTests/FileTextHandlerTests.cs
> +            .BeEquivalentTo(output);
Не проходят тесты

> Path to MyStem.exe is not valid! Change 'PathToMyStem' properties or move MyStem.exe in appropriate folder.

2024-02-03 09:33 UTC, Reltig commented on TagCloud/TagCloudServicesFactory.cs
> +                filter: provider.GetService<IWordFilter>()
Обработается Result.Of

2024-12-10 08:08 UTC, closed without merging