Бабин Георгий
kontur-courses/fp pull request #168
Opened 2024-02-04 12:47 UTC by tripples25

2024-02-05 11:11 UTC, the-homeless-god requested changes

2024-02-05 11:11 UTC, the-homeless-god commented on TagsCloudResult/README.md
> +![example4](https://github.com/tripples25/tdd/blob/8b58d8f0592e3592d28af7ce6bfe3c817a716d16/TagsCloudVisualization/layoutImages/new%20angle%201%20distance%200.5.Png?raw=true)
Спасибо за README, рекомендую отформатировать только его и перенести из заголовков второго уровня информацию про параметры, можно использовать таблички

2024-02-05 11:11 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization.WFApp/Actions/ImageSettingsAction.cs
> +}
В конце файлов нужны пустые строки, можно настроить EditorConfig

2024-02-05 11:11 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization.WFApp/Actions/ImageSettingsAction.cs
> +        if (dialog == DialogResult.OK)
Старайся использовать { } и избегать однострочных выражений

2024-02-05 11:11 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization.WFApp/Actions/SourceSettingsAction.cs
> +    public string Name => "Источник...";
Я бы утащил все тексты в Resources Dictionary

2024-02-05 11:11 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization.WFApp/Program.cs
> +        // container.RegisterType<DocTextReader>().Keyed<TextReader>(FileExtension.Doc).Keyed<TextReader>(FileExtension.Docx);
Избегаем закомменченого кода

2024-02-05 11:11 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization/Common/Result.cs
> +    }
Не понимаю логику

Также классы лучше разнести под namespace в разных файлах

2024-02-05 11:11 UTC, the-homeless-god commented on TagsCloudResult/layoutImages/tags.Png
в названии файлов не следует использовать пробелы, также .png вместо .Png

2024-02-05 15:00 UTC, tripples25 commented on TagsCloudResult/TagsCloudVisualization/Common/Result.cs
> +    }
Result я брал из примера, что предоставили нам в Контуре. None в данном случае используется для представления возвращаемого значения void-методов. Какой-то дополнительной логики этот класс более не несёт.

2024-02-06 12:54 UTC, the-homeless-god requested changes

2024-02-06 12:54 UTC, the-homeless-god commented on TagsCloudResult/README.md
> +![example1](https://github.com/tripples25/fp/blob/1a4585180188efc9c6a35736650295a4e470f916/TagsCloudResult/layoutImages/sample.png?raw=true)
В квадратных скобках переименовать название, у самого файла сделать адекватный путь и название без camelCase к примеру

2024-02-06 12:54 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization.WFApp/Common/PictureBoxImageHolder.cs
> +        Application.DoEvents();
Почему так решил делать?

2024-02-06 12:54 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization.WFApp/Infrastructure/UIActionExtensions.cs
> +    private static ToolStripMenuItem CreateTopLevelMenuItem(MenuCategory category, IList<IUiAction> items)
Почему не фабричный метод, а статические методы?

2024-02-06 12:54 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization.WFApp/Program.cs
> +        container.RegisterType<PictureBoxImageHolder>().As<PictureBoxImageHolder, IImageHolder>().SingleInstance();
Было бы круто добавить здесь комментариев

2024-02-06 12:54 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization/CloudLayouters/CircularCloudLayouter.cs
> +        return point;
Дублирование кода, магические цифры, не хватает SRP

2024-02-06 12:54 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization/Common/ResultOf/None.cs
> +public class None
Снова вопрос к этому файлу, мб анонимные классы использовать вместо этого? Или Generic?

2024-02-06 12:54 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization/Common/ResultOf/ResultExtensions.cs
> +    public static Result<T> AsResult<T>(this T value)
Почему решил делать всё на статике тут?

2024-02-06 12:54 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization/TagsCloudVisualizator.cs
> +                    return tagDraw;
Почему так?

2024-02-06 12:54 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization/TagsCloudVisualizator.cs
> +        return tag.Coeff > 0.75 ? tagsSettings.PrimaryColor : tag.Coeff > 0.35 ? tagsSettings.SecondaryColor
Избавиться от однострочности, нечитаемо, возможно даже стоит добавить комментов

2024-02-06 12:54 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization/TextReaders/DocTextReader.cs
> +    }
А зачем пустой?

2024-02-06 12:54 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization/TextReaders/TxtTextReader.cs
> +    }
Тот же вопрос почему появляются пустые конструкторы?

2024-02-06 12:54 UTC, the-homeless-god commented on TagsCloudResult/layoutImages/sample.png
Красивое 🚀

2024-02-06 15:04 UTC, tripples25 commented on TagsCloudResult/TagsCloudVisualization.WFApp/Common/PictureBoxImageHolder.cs
> +        Application.DoEvents();
Думал запускать цикл при отрисовке тегов, чтобы отрисовывать в real-time. В целом, он теперь не нужен, да и не рекомендуем к использованию, если верить документации и форумам, поэтому убрал.

2024-02-06 15:26 UTC, tripples25 commented on TagsCloudResult/TagsCloudVisualization/TextReaders/DocTextReader.cs
> +    }
Потому что наследуется от абстрактного класса, в котором прописан конструктор. До этого абстрактный класс ещё содержал дополнительную общую логику, но теперь она уже отсутствует. Переписал на использование интерфейса.

2024-02-06 17:03 UTC, tripples25 commented on TagsCloudResult/TagsCloudVisualization/TagsCloudVisualizator.cs
> +        return tag.Coeff > 0.75 ? tagsSettings.PrimaryColor : tag.Coeff > 0.35 ? tagsSettings.SecondaryColor
Переписал, использовав константы и оператор switch.

2024-02-06 17:06 UTC, tripples25 commented on TagsCloudResult/TagsCloudVisualization/TagsCloudVisualizator.cs
> +                    return tagDraw;
Потому что по задумке метод должен вернуть Result с ошибкой на первом теге, который не сумел отрисоваться. Переписал на LINQ, дополнительно выделив методы, убрал часть вложенности.

2024-02-06 21:07 UTC, tripples25 commented on TagsCloudResult/TagsCloudVisualization.WFApp/Infrastructure/UIActionExtensions.cs
> +    private static ToolStripMenuItem CreateTopLevelMenuItem(MenuCategory category, IList<IUiAction> items)
Ну, я не рассчитывал на создание других клиентов или других типов/видов кнопок, поэтому пренебрёг пластичностью и просто создал удобные для себя статические расширения. 
Создал фабрику, правда, в качестве результата там пока ToolStripItem. Это позволит создавать другие типы кнопок, унаследованные от ToolStripItem, но не подменять их другими классами не связанными с ним.

2024-02-07 08:52 UTC, tripples25 commented on TagsCloudResult/TagsCloudVisualization/Common/ResultOf/None.cs
> +public class None
Если использовать анонимные классы, то вместо класса None в Generic придётся прокидывать object, что делает отображаемый результат неоднозначным - бывший void-метод теперь возвращать будет Result<object>. Как по мне - звучит грустно и неоднозначно. 

А с дженериками не очень понял идею.
 
Пока что превратил в абстрактный класс, чтобы нельзя было создать экземпляр.

2024-02-07 09:00 UTC, tripples25 commented on TagsCloudResult/TagsCloudVisualization/Common/ResultOf/ResultExtensions.cs
> +    public static Result<T> AsResult<T>(this T value)
Во-первых, потому что часть методов - методы расширения над Generic'ами. Во-вторых, потому что я могу обращаться сразу же к статическому классу, для того чтобы изучить все имеющиеся у меня методы для Result'а, и потом уже выбрать мне подходящий задав Generic-тип. Ну и в целом мне нравиться такой подход. Структура Result при этом получается не перегруженной и просто отображает нам все доступные поля, которыми она обладает.

2024-02-07 13:19 UTC, the-homeless-god approved these changes
LGTM 🚀 само приложение не потестил, вопросов нет

2024-02-07 13:19 UTC, the-homeless-god commented on TagsCloudResult/README.md
> +![tagcloudsample](layoutImages/sample.png)
исправить tagcloudsample на tag_cloud_sample
исправить layoutImages/ на layout/images/

2024-02-07 13:19 UTC, the-homeless-god commented on TagsCloudResult/TagsCloudVisualization.WFApp/Actions/SaveImageAction.cs
> +
```suggestion

        var res = dialog.ShowDialog();
```

2024-12-10 08:08 UTC, closed without merging