Шпора-2018 Илья Шаков
kontur-courses/fp pull request #17
Opened 2018-12-18 21:05 UTC by eliyy4hu

@tkirill128

2018-12-19 08:58 UTC, eliyy4hu commented
@tkirill

2018-12-19 14:19 UTC, tkirill requested changes

2018-12-19 14:19 UTC, tkirill commented on TagsCloudContainer/TagsCloudContainerApplication.cs
> +            boringWordsRepository.LoadWords(appSettings.BlackListPath);
не проверяется result

2018-12-19 14:19 UTC, tkirill commented on TagsCloudContainer/UI/CLI.cs
> +        private void CheckArguments()
Тут можно переделать на Result

2018-12-19 14:19 UTC, tkirill commented on TagsCloudContainer/UI/CLI.cs
> +            TagsCloudCenter = new Point(ImageSize.GetValueOrThrow().Width, ImageSize.GetValueOrThrow().Height);
Вместо исключений должен использоваться Result.

2018-12-19 14:19 UTC, tkirill commented on TagsCloudContainer/Filtering/FilteringComponent.cs
> +                words = filter.Filter(words).GetValueOrThrow();
тут тоже вместо исключения можно использовать Result

2018-12-20 18:11 UTC, tkirill requested changes

2018-12-20 18:11 UTC, tkirill commented on TagsCloudContainer/TagsCloudContainerApplication.cs
> +                Console.WriteLine(wordsLoadResult.Error);
Эта ошибка должна учитываться в общем Result этого метода.

2020-10-17 22:54 UTC, closed without merging