Трофимов Никита
kontur-courses/fp pull request #175
Opened 2024-02-06 12:36 UTC by WoeromProg

2024-02-10 22:04 UTC, the-homeless-god requested changes

2024-02-10 22:04 UTC, the-homeless-god commented on TagsCloudContainer.csproj
> +      <Folder Include="Images\" />
Давай задокументируем это в README

2024-02-10 22:04 UTC, the-homeless-god commented on TagsCloudContainer/App/ConsoleApp.cs
> +    private readonly IDraw _draw;
Давай использовать свойства и не использовать _

2024-02-10 22:04 UTC, the-homeless-god commented on TagsCloudContainer/App/ConsoleApp.cs
> +public class ConsoleApp : IApp
Не следуешь SRP (single responsibility principle), у тебя точка входа занимается огромным количеством всего, исправить

2024-02-10 22:04 UTC, the-homeless-god commented on TagsCloudContainer/App/ConsoleApp.cs
> +        _settings = settings ?? throw new ArgumentNullException(nameof(settings));
А обработки исключений нет

2024-02-10 22:04 UTC, the-homeless-god commented on TagsCloudContainer/App/ConsoleApp.cs
> +        bitmap.Value.Save(projectDirectory + "\\Images", $"Rectangles{rnd.Next(1, 1000)}", GetImageFormat(_settings.ImageFormat).GetValueOrThrow());
SRP

2024-02-10 22:04 UTC, the-homeless-god commented on TagsCloudContainer/App/ConsoleApp.cs
> +        bitmap.Value.Save(projectDirectory + "\\Images", $"Rectangles{rnd.Next(1, 1000)}", GetImageFormat(_settings.ImageFormat).GetValueOrThrow());
и магические цифры и пути

2024-02-10 22:04 UTC, the-homeless-god commented on TagsCloudContainer/App/ConsoleApp.cs
> +            _ => Result.Fail<ImageFormat>($"Неверный формат изображения: {imageFormat}")
Можно использовать enum

2024-02-10 22:04 UTC, the-homeless-god commented on TagsCloudContainer/App/ConsoleApp.cs
> +            return Result.Fail<string>($"Файл не найден {filename}");
Использовать всегда { }

2024-02-10 22:04 UTC, the-homeless-god commented on TagsCloudContainer/App/ConsoleApp.cs
> +}
в конце файлов пустую строку добавить

2024-02-10 22:04 UTC, the-homeless-god commented on TagsCloudContainer/App/Extensions/BitmapExtension.cs
> +public static class BitmapExtension
Почему статический?

2024-02-10 22:04 UTC, the-homeless-god commented on TagsCloudContainer/App/Extensions/BitmapExtension.cs
> +        bitmap.Save($"{path}\\{filename}.{format}", format);
не хватает обработки исключений

2024-02-10 22:04 UTC, the-homeless-god commented on TagsCloudContainer/Cloud/SpiralFunction.cs
> +        public Result<Point> GetNextPoint()
Нужны комментарии

2024-02-10 22:04 UTC, the-homeless-god commented on TagsCloudContainer/Console/CommandLineOptions.cs
> +        //@"C:\Users\nikit\RiderProjects\di\TagsCloudContainer\TextFiles\Boring.txt";
?

2024-02-10 22:04 UTC, the-homeless-god commented on TagsCloudContainer/DrawRectangle/RectangleDraw.cs
> +
Разбить на подметоды

2024-02-10 22:04 UTC, the-homeless-god commented on TagsCloudContainerTests/FileReaderTest.cs
> +        //Directory.GetParent(Environment.CurrentDirectory).Parent.Parent.FullName + "\\TextFiles\\" + fileName
?

2024-02-21 21:26 UTC, the-homeless-god requested changes

2024-02-21 21:26 UTC, the-homeless-god commented on TagsCloudContainer.csproj
> +    </ItemGroup>
Это точно тут нужно?

2024-02-21 21:26 UTC, the-homeless-god commented on TagsCloudContainer/App/ConsoleApp.cs
> +public class ConsoleApp : IApp
Все еще актуальный комментарий

2024-02-21 21:26 UTC, the-homeless-god commented on TagsCloudContainer/App/ConsoleApp.cs
> +            _ => Result.Fail<ImageFormat>($"Неверный формат изображения: {imageFormat}")
Все еще актуальный комментарий

2024-02-21 21:26 UTC, the-homeless-god commented on TagsCloudContainer/App/AppExtensions/PathImage.cs
> +            _ => Result.Fail<ImageFormat>($"Неверный формат изображения: {imageFormat}")
Давай будем использовать enum для ключей?

2024-02-21 21:26 UTC, the-homeless-god commented on TagsCloudContainer/Cloud/CircularCloudLayouter.cs
> +            if(rectangle.IsIntersectOthersRectangles(_rectangles))
Куда-то делось форматирование кода + не хватает try-catch

2024-02-21 21:26 UTC, the-homeless-god commented on TagsCloudContainer/Cloud/CircularCloudLayouter.cs
> +        return newRectangle;
Дублирование + магия + магические числа

2024-02-21 21:26 UTC, the-homeless-god commented on TagsCloudContainer/Cloud/CircularCloudLayouter.cs
> +        }
Опять дублирование + магия + отсутствие try-catch + сложно читать, а значит надо упрощать

2024-02-21 21:26 UTC, the-homeless-god commented on TagsCloudContainer/Console/CommandLineOptions.cs
> +    [Option('b', "Boring", Required = false, HelpText = "Укажите путь до файла со скучными словами", Default = "../../../TextFiles/Boring.docx")]
Этот файл точно есть в репо?

2024-02-21 21:26 UTC, the-homeless-god commented on TagsCloudContainer/DrawRectangle/RectangleDraw.cs
> +public class RectangleDraw : IDraw
Отсутствие SOLID-а в целом, нужно дробить + оптимизировать

2024-02-21 21:26 UTC, the-homeless-god commented on TagsCloudContainer/WordProcessing/Result.cs
> +}
Поплыло форматирование, плюс не стоит хранить по паре классов в одном файле

2024-02-23 11:50 UTC, WoeromProg commented on TagsCloudContainer/Console/CommandLineOptions.cs
> +    [Option('b', "Boring", Required = false, HelpText = "Укажите путь до файла со скучными словами", Default = "../../../TextFiles/Boring.docx")]
![репо](https://github.com/kontur-courses/fp/assets/119159723/e301dd39-5269-4bd8-be2e-c59062c4828d)

2024-02-25 18:09 UTC, WoeromProg commented on TagsCloudContainer/Cloud/CircularCloudLayouter.cs
> +            if(rectangle.IsIntersectOthersRectangles(_rectangles))
Какую ошибку здесь можно отлавливать?

2024-02-26 21:08 UTC, the-homeless-god approved these changes

2024-12-10 08:08 UTC, closed without merging