Алешев Руслан
kontur-courses/fp pull request #176
Opened 2024-02-06 15:55 UTC by artBETEP

@Grantsev
Задание TagsCloudResult

2024-02-08 16:15 UTC, gisinka requested changes

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/ResutlTests/CLIParsersTests.cs
> +            //commandLine.FontFamily = "Arial";
Надо бы прибрать лишнее

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/ResutlTests/PointsProviderTests.cs
> +            // Assert
Эти комменты точно нужны?

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/TagsCloudContainer/CLI/CommandLineOptions.cs
> +            var c = colors.Split(',').Select(x => Color.FromName(x)).ToList();
Давай называть переменные по сути)

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/TagsCloudContainer/FrequencyAnalyzers/FrequencyAnalyzer.cs
> +        public void Analyze(string text, string exclude = "")
Может сделать, чтобы из Analyze сразу проанализированный текст возвращался?

У тебя общая хранилка фриквенсей, класс не переиспользуем в плане, один текст проанализировал, для второго уже результат будет искажен

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/TagsCloudContainer/FrequencyAnalyzers/TextPreprocessing.cs
> +                return;
Обработать бы ошибку ненайденного файла

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/TagsCloudContainer/Result/ErrorParser.cs
> +    public static class ErrorParser
А что он собственно парсит?

Хэлпер какой-то, но никак не парсер

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/TagsCloudContainer/Result/Result.cs
> +    public class None
Смысла в этом классе особо не вижу

Имхо, лучше реализовать Result без результата, определить туда поля для ошибок, свойство IsSuccess и прочее

А Result отнаследовать от него, тогда они будут реализовывать один общий корень, при этом не нужны будут классы-заполнялки, как этот

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/TagsCloudContainer/Result/Result.cs
> +            if (!input.IsSuccess) handleError(input.Error);
Непривычно видеть однострочные if'ы

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/TagsCloudContainer/TagCloudBuilder/NormalPointsProvider.cs
> +        private const int maxPointsCount = 10000000;
Зачем это ограничение?

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/TagsCloudContainer/TagCloudBuilder/NormalPointsProvider.cs
> +        private Random rnd = new();
Почему это не readonly?

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/TagsCloudContainer/TagCloudBuilder/RandomPointsProvider.cs
> +    public class RandomPointsProvider : IPointsProvider
Комменты как в соседнем классе

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/TagsCloudContainer/TagCloudBuilder/RandomPointsProvider.cs
> +        public void Initialize(Point center)
Для этого есть конструктор

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/TagsCloudContainer/TagCloudBuilder/TagsCloudLayouter.cs
> +                    yield return Result.Fail<TextImage>("Can't place more rectangles. Try to increase canvas size");
А есть тут какой-то сакральный смысл в ленивости вычислений? На чем экономим?

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/TagsCloudContainer/Visualizer/Visualizer.cs
> +            var gr = Graphics.FromImage(image);
IDisposable жеж

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/ResutlTests/CLIParsersTests.cs
> +namespace ResutlTests
Очепятка

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/TagsCloudContainer/Program.cs
> +            Visualizer.Draw(appSettings.DrawingSettings.Size,
Ето не функциональное программирование, построй логику на Result и Then

что-то типа, должен получиться лаконичный пайплайн обработки:
```
 var res = fileReaderFactory
            .Create(settings.InputPath)
            .Then(fileReader=> fileReader.GetLines(settings.InputPath))
            .Then(lemmatizer.GetLemmas)
            .Then(filter.FilterWords)
            .Then(weigher.GetWeightedWords)
            .Then(painter.CreateImage)
            .Then(bitmap => saver.Save(bitmap, settings.OutputPath, settings.OutputFormat));

        if (!res.IsSuccess)
            Console.Write(res.Error);
```

2024-02-08 16:15 UTC, gisinka commented on TagCloud3/TagsCloudContainer/Result/Result.cs
> +            ErrorParser.Critical(Error);
Метод, который говорит, что кинет исключение - убивает программу, а не прокидывает его наверх, таких приколов быть не должно

Зона ответственности метода GetValueOrThrow вообще никак не натягивается на убивание программы, это должно быть на уровне твоего приложения выше, если вообще должно быть

2024-02-08 16:49 UTC, artBETEP commented on TagCloud3/TagsCloudContainer/TagCloudBuilder/RandomPointsProvider.cs
> +        public void Initialize(Point center)
Наследие DI

2024-02-08 16:53 UTC, artBETEP commented on TagCloud3/TagsCloudContainer/TagCloudBuilder/TagsCloudLayouter.cs
> +                    yield return Result.Fail<TextImage>("Can't place more rectangles. Try to increase canvas size");
Смысл в ленивости: Точки - суть кандидаты для размещения слов. Врят ли имеет смысл вычислять все точки, если нам надо будет разместить лишь пару слов.
Еще, думаю тут стоит переделать на Result<IEnumerable<Point>>

2024-02-08 16:56 UTC, artBETEP commented on TagCloud3/TagsCloudContainer/TagCloudBuilder/NormalPointsProvider.cs
> +        private const int maxPointsCount = 10000000;
Как минимум на случай того, если кто-то попробует сделает Count, foreach и т.п. на последовательности.

2024-02-11 06:53 UTC, artBETEP commented on TagCloud3/TagsCloudContainer/Result/ErrorParser.cs
> +    public static class ErrorParser
Удалил этот класс, сейчас в нем нет надобности.

2024-02-11 06:53 UTC, artBETEP commented on TagCloud3/TagsCloudContainer/Result/Result.cs
> +    public class None
Переписал класс Result.

2024-02-11 07:55 UTC, artBETEP commented on TagCloud3/TagsCloudContainer/Visualizer/Visualizer.cs
> +            var gr = Graphics.FromImage(image);
Класс переименован в Painter, интерфейс реализован.

2024-02-11 07:55 UTC, artBETEP commented on TagCloud3/TagsCloudContainer/Program.cs
> +            Visualizer.Draw(appSettings.DrawingSettings.Size,
Логику переделал

2024-02-12 05:02 UTC, gisinka commented on TagCloud3/TagsCloudContainer/TagCloudBuilder/NormalPointsProvider.cs
> +        private const int maxPointsCount = 10000000;
Ну, в целом, если генерить массив случайный и его сортировать много раз, то это тоже будет работать не супер быстро, но тут вопрос: а зачем? Я к тому, что любой код можно заставить работать долго, но не просто же так это делать

2024-02-12 05:08 UTC, gisinka commented on TagCloud3/TagsCloudContainer/Program.cs
> +                var res = FrequencyAnalyzer.Analyze(rawText.GetValueOrDefault(), appSettings.FilterFile)
RawText можно тож через Then передавать же, не?
Тебе просто нужен Then
```
public static Result<TOutput> Then<TInput, TOutput>(this Result<TInput> input, Func<TInput, Result<TOutput>> continuation)
    {
        return input.IsSuccess && input.Value != null
            ? continuation(input.Value)
            : Fail<TOutput>(input.Error);
    }
```

Суть - не кидаешь эксепшоны, складываешь в монаду ошибки, так тебе не понадобится GetValueOrDefault() и тд

2024-12-10 08:08 UTC, closed without merging