Мохов Даниил
kontur-courses/fp pull request #33
Opened 2019-12-15 09:01 UTC by Kamikoto-sama

@tkirill

2019-12-16 18:46 UTC, tkirill requested changes

2019-12-16 18:46 UTC, tkirill commented on TagsCloud/LayoutConstructor.cs
> +			});
Тут через `Result.Then` можно сделать или что-то мешает?

2019-12-16 18:46 UTC, tkirill commented on TagsCloud/CircularCloudLayouter.cs
> +				throw new ArgumentException("Size values must be non-negative");
Нужно переделать на Result

2019-12-16 18:46 UTC, tkirill commented on TagsCloud/WordsProcessor.cs
> +			if (!filteredWords.IsSuccess)
Этот `if` можно заменить на `Result.Then` или что-то мешает?

Если проблема в `foreach`, то как минимум можно вынести подсчёт в приватный метод, а вообще можно использовать [.ToLookup](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.tolookup?view=netframework-4.8), [.Aggregate](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.aggregate?view=netframework-4.8) или написать свой extension навроде `IEnumerable.CountFrequency`.

2019-12-16 18:46 UTC, tkirill commented on TagsCloud/WordsProcessor.cs
> +			if (!words.IsSuccess)
Этот `if` можно заменить на `Result.Then`, только нужно придумать как сделать дальше проверку слов.

Например, можно сделать примерно так:

```
Result<ICollection<string>> FilterWords() => textReader.Read().Then(CheckWords);

Result<ICollection<string>> CheckWords(string[] words) => // реализовать с помощью .Where и .All

// Сделать такие хелперы
public static Result<bool> All<T>(this IEnumerable<T> sequence, Func<T, Result<bool>> filter)
public static Result<ICollection<T>> Where<T>(this IEnumerable<T> sequence, Func<T, Result<bool>> filter)
```

2019-12-16 18:46 UTC, tkirill commented on TagsCloud/TagsProcessor.cs
> +				throw new ArgumentException("MinFontSize must be grater than 1");
Нужно переделать исключения на Result

2019-12-17 10:41 UTC, Kamikoto-sama commented on TagsCloud/LayoutConstructor.cs
> +			});
Исправил.

2019-12-17 11:27 UTC, Kamikoto-sama commented on TagsCloud/CircularCloudLayouter.cs
> +				throw new ArgumentException("Size values must be non-negative");
Исправил.

2019-12-17 11:58 UTC, Kamikoto-sama commented on TagsCloud/WordsProcessor.cs
> +			if (!filteredWords.IsSuccess)
Исправил.

2019-12-17 12:43 UTC, Kamikoto-sama commented on TagsCloud/WordsProcessor.cs
> +			if (!words.IsSuccess)
Исправил.

2019-12-17 12:50 UTC, Kamikoto-sama commented on TagsCloud/TagsProcessor.cs
> +				throw new ArgumentException("MinFontSize must be grater than 1");
Исправил

2019-12-18 10:38 UTC, tkirill approved these changes

2020-10-17 22:55 UTC, closed without merging