Панков Данил
kontur-courses/fp pull request #34
Opened 2019-12-15 10:00 UTC by MrTimeChip

@RawRCoder

2019-12-16 11:11 UTC, RawRCoder commented on TagsCloudResult/TagsCloud.cs
> +            parsedWords = wordsParser.Parse().ToList();
Не совсем про текущую задачу, но не мог пройти мимо.
У класса очень богатый публичный интерфейс. Нельзя назвать какой-то одной задачи, за которую отвечает этот класс, он занимается всем и сразу. Чтобы нарисовать облако тегов придётся дернуть в правильной последовательности несколько абсолютно ничем формально не связанных методов одного класса. Это точно на чистый код похоже?

2019-12-16 12:31 UTC, RawRCoder requested changes

2019-12-16 12:31 UTC, RawRCoder commented on TagsCloudResult/CloudVisualizers/ImageSaving/ImageSaver.cs
> +            bitmap.Save(settings.Path, settings.Format);
В этой строчке есть вагон и маленькая тележка причин, по которой в ней может всё развалиться.
- Путь до файла не найден
- Файл заблокирован другим процессом
- Путь до файла - null
- Неподдерживаемый формат
- System.Runtime.InteropServices.ExternalException 
- Сетевые ошибки (например, если сохраняем по UNC)
- ...

2019-12-16 12:31 UTC, RawRCoder commented on TagsCloudResult/CloudVisualizers/ImageSaving/SupportedImageFormats.cs
> +                case ".png":
Может стоило просто "откусить" точку с начала строки?

2019-12-16 12:31 UTC, RawRCoder commented on TagsCloudResult/CloudLayouters/CloudLayouter.cs
> +            var countDifference = maxCount - minCount == 0 ? 1 : maxCount - minCount;
Зачем здесь нужно преобразование в `double`?

2019-12-16 12:31 UTC, RawRCoder commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            var bitmap = new Bitmap(settings.Width, settings.Height);
Здесь тоже возможны исключения.

Попробуй указать ширину и высоту в 32000?

2019-12-16 12:31 UTC, RawRCoder commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            (xRatio, yRatio) = ((float) settings.Width / xDifference, (float) settings.Height / yDifference);
Зачем так?, Почему не 
```
var xRatio = ...; 
var yRatio = ...
```

2019-12-16 12:31 UTC, RawRCoder commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            return colorList;
nit: можно было сделать генератор

2019-12-16 12:31 UTC, RawRCoder commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +                        var brush = new SolidBrush(settings.Palette.PrimaryColor);
Зачем создавать объект на каждое слово? Если можно его создать один раз, т.к. PrimaryColor не меняется (не должен)

2019-12-16 12:31 UTC, RawRCoder commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            var minY = rectangles.OrderBy(rect => rect.Y).First().Y;
nit: Почему не `var minX = rectangles.Min(rect => rect.X); ...`?

2019-12-16 12:31 UTC, RawRCoder commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            var rectangles = wordsList.Select(w => w.Rectangle).ToList();
nit: Зачем `ToList`, если достаточно `ToArray`?

2019-12-16 12:31 UTC, RawRCoder commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            IEnumerable<CloudVisualizationWord> words,
nit: see https://www.jetbrains.com/help/resharper/PossibleMultipleEnumeration.html

Предлагаю поменять на `IReadOnlyCollection`

2019-12-16 12:31 UTC, RawRCoder commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            var maxY = rectangles.OrderBy(rect => rect.Bottom).Last().Bottom;
`rectangles.Max(r => r.Right); ... `?

2019-12-16 12:31 UTC, RawRCoder commented on TagsCloudResult/ApplicationRunning/Commands/VisualizeCommand.cs
> +            return Check.ArgumentsCountIs(args, 8)
nit: Можно было просто поставить это - https://www.nuget.org/packages/CommandLineParser/

2019-12-16 12:31 UTC, RawRCoder commented on TagsCloudResult/ApplicationRunning/Commands/VisualizeCommand.cs
> +            var font = new Font(fontName, 16);
Здесь всё развалится, как только указанный шрифт не будет найден в системе

2019-12-16 14:08 UTC, MrTimeChip commented on TagsCloudResult/CloudVisualizers/ImageSaving/ImageSaver.cs
> +            bitmap.Save(settings.Path, settings.Format);
Исправил. Теперь возвращает Result с описанием проблемы.

2019-12-16 14:09 UTC, MrTimeChip commented on TagsCloudResult/CloudVisualizers/ImageSaving/SupportedImageFormats.cs
> +                case ".png":
Действительно. Глупая ошибка - исправил.

2019-12-16 14:12 UTC, MrTimeChip commented on TagsCloudResult/CloudLayouters/CloudLayouter.cs
> +            var countDifference = maxCount - minCount == 0 ? 1 : maxCount - minCount;
Это преобразование нужно было для сохранения точности при делении. Но по какой-то причине я поставил преобразование в самое нелогичное место. Исправил.

2019-12-16 14:26 UTC, MrTimeChip commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            var bitmap = new Bitmap(settings.Width, settings.Height);
Исправил. Добавил проверку на исключение. Правда, не смог указать более детальные описания ошибок - просто пробрасываю сообщение исключения. К сожалению, в доках не написано о всевозможных исключениях и их описаниях, поэтому не могу специализировать. Будет ли этого достаточно?

2019-12-16 14:40 UTC, MrTimeChip commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            (xRatio, yRatio) = ((float) settings.Width / xDifference, (float) settings.Height / yDifference);
Честно говоря - осталось с прошлой реализации, когда я использовал дополнительные методы для получения соотношений x и y, из-за которых не мог вынести это в отдельные методы. 
Сейчас заменил на отдельные методы - легче читать и отлаживать, но вопрос - насколько критично использование tuple? Всё таки - операции идентичны, в случае ошибки отлаживание не будет большой проблемой.

2019-12-16 14:41 UTC, MrTimeChip commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +                        var brush = new SolidBrush(settings.Palette.PrimaryColor);
Действительно - не имеет смысла, я даже как-то и не заметил. Исправил.

2019-12-16 14:49 UTC, MrTimeChip commented on TagsCloudResult/ApplicationRunning/Commands/VisualizeCommand.cs
> +            var font = new Font(fontName, 16);
Так не упадёт же? 
![image](https://user-images.githubusercontent.com/40389711/70916229-5e3e1c00-202c-11ea-9597-7688b5357a89.png)

2019-12-16 14:53 UTC, MrTimeChip commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            return colorList;
Действительно, выглядит практичней.

2019-12-16 14:54 UTC, MrTimeChip commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            var minY = rectangles.OrderBy(rect => rect.Y).First().Y;
Да, логично. Просто руководствовался сортированием в своей голове - так написал и в коде.

2019-12-16 14:58 UTC, MrTimeChip commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            var maxY = rectangles.OrderBy(rect => rect.Bottom).Last().Bottom;
Исправил.

2019-12-16 15:00 UTC, MrTimeChip commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            var rectangles = wordsList.Select(w => w.Rectangle).ToList();
Да, имеет смысл. Исправил.

2019-12-16 15:05 UTC, MrTimeChip commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            IEnumerable<CloudVisualizationWord> words,
Прочитал, суть ясна. Заменил на IReadOnlyCollection.

2019-12-17 11:06 UTC, RawRCoder commented on TagsCloudResult/CloudLayouters/CloudLayouter.cs
>              var countDifference = maxCount - minCount == 0 ? 1 : maxCount - minCount;
nit: тут тоже можно было упростить до `max... == min... ? ...`

2019-12-17 11:07 UTC, RawRCoder commented on TagsCloudResult/CloudLayouters/CloudLayouter.cs
>              var countDifference = maxCount - minCount == 0 ? 1 : maxCount - minCount;
Или до `Math.Max(max-min, 1)`

2019-12-17 11:14 UTC, RawRCoder commented on TagsCloudResult/CloudLayouters/CloudLayouter.cs
> +            var countDifference = maxCount - minCount == 0 ? 1 : maxCount - minCount;
Можно было ещё `Multiplier` double-ом сделать, так вообще явных преобразований не пришлось бы делать.

2019-12-17 11:17 UTC, RawRCoder commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            var bitmap = new Bitmap(settings.Width, settings.Height);
Достаточно - да наверное.
Вообще, я бы предложил примерно такой подход. Если не получается полностью осмысленно переписать описание ошибки (общий непредсказуемый случай) - то текст ошибки = `Такая то операция не удалась - {ex.Message}`. В идеале - залогировать со стектрейсом и всем остальным, что есть в исключении. Иногда там бывают ключевые для отладки данные

2019-12-17 11:20 UTC, RawRCoder commented on TagsCloudResult/CloudVisualizers/BitmapMakers/DefaultBitmapMaker.cs
> +            (xRatio, yRatio) = ((float) settings.Width / xDifference, (float) settings.Height / yDifference);
Да вообще не очень важно. Просто выглядит странно и не логично.

Но есть ещё пара соображений - исходя из которых таплы нужны очень редко и преимущественно для наколеночных решений. Если одна и та же сигнатура/набор полей встречается в нескольких местах - правильнее просто сделать класс со всеми этими полями/свойствами. Возможно структуру. Иначе - зачастую удобнее анонимные объекты

2019-12-17 11:30 UTC, RawRCoder commented on TagsCloudResult/ApplicationRunning/Commands/VisualizeCommand.cs
> +            var font = new Font(fontName, 16);
хмммммммммммммммммммммммммммммм. И правда

2020-10-17 22:55 UTC, closed without merging