Миргородский Николай
kontur-courses/fp pull request #35
Opened 2019-12-15 13:46 UTC by IAmTomaton

@Leofwin

2019-12-18 06:57 UTC, Leofwin requested changes

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Result.cs
> +        }
не хватает переноса строки

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Result.cs
> +        public string Error { get; }
у тебя в одном месте поля выше конструктора объявлены, в другом ниже. давай весь проект к единообразию приведем
я предлагаю такой порядок:
```
приватные поля
публичные поля
конструктор
публичные методы
приватные методы

````

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Result.cs
> +        internal T Value { get; }
почему `itnernal`?

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Result.cs
> +        }
не хватает переноса строки

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Result.cs
> +        }
не хватает переноса строки

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Result.cs
> +            Func<TInput, TOutput> continuation)
Func и Action - действия, давай переменную глаголом назовем

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainerTests/Program.cs
> +    class Program
почему не сделать тесты библиотекой? тогда не нужна будет эта точка входа

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Program.cs
> +        public class Options
а давай вынесем в отдельный файл

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Program.cs
> +        static void Main(string[] args)
давай явно прописывать модификаторы доступа

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Program.cs
> +        private static Result<Bitmap> Work(Options o)
давай не будем использовать однобуквенные переменные. при чтении кода можно легко забыть что именно это за объект: `orange`, `oval`?
Соотвественно, нужно везде поправить

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Program.cs
> +                               new NamedParameter("font", new Font(o.Font, o.Size)),
куда-то они далеко уехали здесь :)

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Program.cs
> +            containerBuilder.RegisterType<CircularCloudLayouter>().As<ICloudLayouter>().WithParameter("center", new Point());
давай не будем писать строки длиной >150 символов.
у меня FullHD экран и мне почти мотать приходится.

Соответственно, нужно везде поправить

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Program.cs
> +    class Program
`public`

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Program.cs
> +            var containerBuilder = new ContainerBuilder();
давай вынесем конфигурацию контейнера в отдельную функцию - очень громоздко в этом методе выглядит

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/TagsCloudGenerators/TagsCloudGenerator.cs
> +using System;
нигде не используются

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/TagsCloudGenerators/TagsCloudGenerator.cs
> +        private IWordCounter wordCounter;
все поля могут быть `readonly`

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Readers/SimpleReader.cs
> +        private string path { get; }
`readonly`
больше писать про это не буду - нужно везде поправить

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Readers/SimpleReader.cs
> +using System.Linq;
нигде не используется.
больше писать про это не буду - нужно везде поправить

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Readers/SimpleReader.cs
> +        private string path { get; }
`Path`

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Readers/SimpleReader.cs
> +    public class SimpleReader : IReader
очень странная реализация в классе. давай лучше для каждого формата сделаем отдельный `IReader`, а этот класс преобразуем в фабрику `IReader`'ов. то есть она будет возвращать нужный в зависимости от расширения

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Readers/SimpleReader.cs
> +            if (!File.Exists(path))
эту проверку нужно вынести в начало метода

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Readers/SimpleReader.cs
> +            var stream = new StreamReader(path);
тебе решарпер не подсказывает, что ты не вызываешь `Dispose()` у объекта? 
Советую использовать `using`

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/Readers/SimpleReader.cs
> +            for (int i = 1; i < doc.Paragraphs.Count; i++)
`var`

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/WordPreprocessors/IWordPreprocessor.cs
> +        Result<ProcessedWord[]> WordPreprocessing(string[] text);
функция должна иметь глагол в названии

2019-12-18 06:57 UTC, Leofwin commented on TagsCloudContainer/CloudLayouters/MyConverter.cs
> +    public static class MyConverter
раз используется только в тестах, значит ему там самое место

2019-12-18 12:45 UTC, IAmTomaton commented on TagsCloudContainer/CloudLayouters/MyConverter.cs
> +    public static class MyConverter
Это не для тестов. Это визуализация из первого клауда

2019-12-18 15:37 UTC, IAmTomaton commented on TagsCloudContainer/Result.cs
> +        }
Все резалты я взял из репозитория) Эт не я писал)

2019-12-19 11:23 UTC, Leofwin requested changes
к сожалению, тесты так и не запускаются.
а еще не все замечания исправлены.

2019-12-19 11:23 UTC, Leofwin commented on TagsCloudContainer/Readers/SimpleReader.cs
> +    public class SimpleReader : IReader
жаль, что ничего не изменилось

2019-12-19 11:23 UTC, Leofwin commented on TagsCloudContainer/Result.cs
> +        internal T Value { get; }
осталось `internal`

2019-12-19 11:23 UTC, Leofwin commented on TagsCloudContainerTest/SimpleReaderTests.cs
> +            Console.WriteLine(TestContext.CurrentContext.TestDirectory);
думаю, что он здесь не нужен

2020-10-17 22:55 UTC, closed without merging