Субачев Сергей
kontur-courses/fp pull request #39
Opened 2019-12-15 18:39 UTC by SergeySubachev

Наставник - Карпова Оля @scklepova

2019-12-16 19:54 UTC, scklepova requested changes

2019-12-16 19:54 UTC, scklepova commented on TagsCloud/FileParsers/DocParser.cs
> +            return Result.Of(() => ImmutableList<string>.Empty.AddRange("Съешь ещё этих мягких французских булок да выпей же чаю".Split(' ')));
У `ImmutableList` есть более подходящий метод для создания коллекции. Но не конструктор, да. 
И замечание не только к этому месту в коде относится. Поищи ещё подобные использования.

2019-12-16 19:54 UTC, scklepova commented on TagsCloud/FileParsers/TxtParser.cs
> +                .Then(lines => ImmutableList<string>.Empty.AddRange(lines.SelectMany(line => line.Split(separators, StringSplitOptions.RemoveEmptyEntries))));
Почитай про метод `Split()` без аргументов. Это поможет тебе избавиться от списка разделителей (с ним очень легко пропустить какой-нибудь символ-разделитель. Например, у тебя нет двоеточия и точки с запятой)

2019-12-16 19:54 UTC, scklepova commented on TagsCloud/Layouters/CircularCloudLayouter.cs
> +                for (var i = 1; i < sortedItems.Count; i++)
Можно добавить декларативности и заменить цикл на `Enumerable.Range`, как на паре учили

2019-12-16 19:54 UTC, scklepova commented on TagsCloud/Renderers/ColoredRenderer.cs
>              if (layoutItems.Count() == 0)
Тут решарпер подсказывает использовать другой метод LINQ

2019-12-16 19:54 UTC, scklepova commented on TagsCloud/Renderers/ColoredRenderer.cs
>  ﻿using System;
Держи код в чистоте - убирай всё неиспользуемое, в том числе импорты. 
Кстати, у решарпера есть фича, позволяющая навести порядок в один хоткей. Погугли. Ключевые слова "code cleanup"

2019-12-16 19:54 UTC, scklepova commented on TagsCloud/WordsFiltering/WasteWordsFilter.cs
> +                    .Where(grInfo => (grInfo.Length == 2 || (grInfo.Length >= 3 && grInfo[2] != "сокр")) && allowDict.TryGetValue(grInfo[1], out var isAllow) && isAllow)
Допустимо писать несколько вызовов Where, чтобы не порождать длинные условия

2019-12-16 19:54 UTC, scklepova commented on TagsCloud/WordsLoader.cs
> +                .Then(fileExtension => parsers.FirstOrDefault(p => p.FileExtensions.Any(ext => ext == fileExtension)))
Если заменить вызов на First, можно будет не проверять на null парсер на следующем шаге. Если коллекция будет пустая, First бросит исключение, которое поймает .Then

2019-12-16 19:54 UTC, scklepova commented on TagsCloud/WordsFiltering/WasteWordsFilter.cs
> +                .Then(output => Result.Of(() => File.ReadAllLines(output)).RefineError($"Can't read file '{output}'."))
Если подобных кейсов много, можно создать перегрузку для .Then, которая будет принимать обычный Action или Func, а внутри оборачивать его вызов в Result.Of

2019-12-18 17:02 UTC, SergeySubachev commented on TagsCloud/FileParsers/DocParser.cs
> +            return Result.Of(() => ImmutableList<string>.Empty.AddRange("Съешь ещё этих мягких французских булок да выпей же чаю".Split(' ')));
поправил

2019-12-18 17:04 UTC, SergeySubachev commented on TagsCloud/Layouters/CircularCloudLayouter.cs
> +                for (var i = 1; i < sortedItems.Count; i++)
Поправил, но вообще, на счет того, чтобы for менять Enumerable.Range - мне это не всегда нравится. А на паре, как ты говоришь, на которой это объясняли меня не было, я же не студент )) 
Есть какая-нибудь ссылка на презентацию, мотивирующую делать это? Хотелось бы посмотреть, потому что, видимо, это не всегда оправдано, по крайней мере, например, в учебных примерах, которые мы проходим на шпоре - вообще практически нигде нет такого...

2019-12-18 17:04 UTC, SergeySubachev commented on TagsCloud/Renderers/ColoredRenderer.cs
>              if (layoutItems.Count() == 0)
Решарпера нет, ну понял, да, это видимо чтобы всю коллекцию не перебирать - заменил на IsEmpty или !Any()

2019-12-18 17:05 UTC, SergeySubachev commented on TagsCloud/WordsFiltering/WasteWordsFilter.cs
> +                    .Where(grInfo => (grInfo.Length == 2 || (grInfo.Length >= 3 && grInfo[2] != "сокр")) && allowDict.TryGetValue(grInfo[1], out var isAllow) && isAllow)
Поправил

2019-12-18 17:05 UTC, SergeySubachev commented on TagsCloud/WordsLoader.cs
> +                .Then(fileExtension => parsers.FirstOrDefault(p => p.FileExtensions.Any(ext => ext == fileExtension)))
Поправил

2019-12-18 17:06 UTC, SergeySubachev commented on TagsCloud/WordsFiltering/WasteWordsFilter.cs
> +                .Then(output => Result.Of(() => File.ReadAllLines(output)).RefineError($"Can't read file '{output}'."))
Нет, не надо. Then и так принимает обычный Action. Просто в данном случае я засунул Result.Of внутрь Then для того, чтобы конкретно у этого Result заменить сообщение об ошибке (RefineError), если не сможет прочитать файл output.

2019-12-18 17:06 UTC, SergeySubachev commented on TagsCloud/Renderers/ColoredRenderer.cs
>  ﻿using System;
С решарпером хорошо... Мне приходится постоянно тыкать контекстное меню "Remove and sort usings". Напрягает конечно... И, конечно, бывает забываю...

2019-12-18 17:12 UTC, SergeySubachev commented on TagsCloud/FileParsers/TxtParser.cs
> +                .Then(lines => ImmutableList<string>.Empty.AddRange(lines.SelectMany(line => line.Split(separators, StringSplitOptions.RemoveEmptyEntries))));
Почитал, удобно!, но не понял почему это работает...
В документации написано, что если аргументы пустые - разделяет по символам, которые IsWhiteSpace. Но в справке по IsWhiteSpace - ничего не говорится про знаки пунктуации... 
https://docs.microsoft.com/en-us/dotnet/api/system.char.iswhitespace?view=netframework-4.8
1) Почему они тоже учитываются?
2) Придется дополнительно проверять на пустые строки (если например два разделителя подряд будут), т.к. в StringSplitOptions это не получится указать.

2019-12-19 14:32 UTC, scklepova commented on TagsCloud/FileParsers/TxtParser.cs
> +                .Then(lines => ImmutableList<string>.Empty.AddRange(lines.SelectMany(line => line.Split(separators, StringSplitOptions.RemoveEmptyEntries))));
1. Хм, про знаки препинания в этом методе я не задумывалась... вообще-то он не должен по ним делить, так что да, здесь не зайдет такое.
2. Эту проблему легко решить: можно просто передать пустой массив разделителей, и тогда можно использовать StringSplitOptions

2019-12-19 14:34 UTC, scklepova commented on TagsCloud/Layouters/CircularCloudLayouter.cs
> +                for (var i = 1; i < sortedItems.Count; i++)
Под парой я имела в виду занятие, на котором рассказывали про функциональное программирование. Презентация, по которой скорее всего вели занятие, лежит в том же репозитории, что и домашка.

2019-12-19 15:04 UTC, SergeySubachev commented on TagsCloud/FileParsers/TxtParser.cs
> +                .Then(lines => ImmutableList<string>.Empty.AddRange(lines.SelectMany(line => line.Split(separators, StringSplitOptions.RemoveEmptyEntries))));
Нашел способ лучше - с помощью Regex

2019-12-19 15:14 UTC, SergeySubachev commented on TagsCloud/Layouters/CircularCloudLayouter.cs
> +                for (var i = 1; i < sortedItems.Count; i++)
Ага, понял. Ну вот я и говорю, что кроме презентаций - такое в учебных проектах шпоры практически нигде увидишь больше)

2019-12-19 15:16 UTC, SergeySubachev commented on TagsCloud/Layouters/CircularCloudLayouter.cs
> +                for (var i = 1; i < sortedItems.Count; i++)
..хотя много таких мест типа:
for (int y = 0; y < Height; y++)
    for (int x = 0; x < Width; x++)

2019-12-20 05:58 UTC, scklepova commented on TagsCloud/Layouters/CircularCloudLayouter.cs
> +                for (var i = 1; i < sortedItems.Count; i++)
`Enumerable.Range` скорее просто альтернативный вариант написать `for`. Более fluent вариант. В продакш коде всё же чаще можно использовать `foreach`. С учебной целью - почему бы не попробовать Enumerable.Range)

2020-10-17 22:55 UTC, closed without merging