Рыкалов Глеб
kontur-courses/fp pull request #42
Opened 2019-12-15 20:42 UTC by RGleb

@RawRCoder

2019-12-16 13:24 UTC, RawRCoder requested changes

2019-12-16 13:24 UTC, RawRCoder commented on TagsCloud/TagsCloudConsoleClient/EntryPoint.cs
> +            Console.WriteLine(new ParserOptionsHelp(container).GenerateHelp());
nit: Зочем? CommandLine сам это напишет, если не сможет что-нибудь разобрать

2019-12-16 13:24 UTC, RawRCoder commented on TagsCloud/TagsCloudConsoleClient/ParserOptions.cs
> +        public IEnumerable<string> Colors { get; set; }
nit: Почему бы просто не написать здесь что-нибудь типа `IReadOnlyCollection` и не страдать с `.ElementAt`?

2019-12-16 13:24 UTC, RawRCoder commented on TagsCloud/TagsCloudGenerator_Tests/SingletonScopeInstancesContainer.cs
> +        public Type Get<Type>() => container.Resolve<Type>();
Зачем так? Может не надо? Дженериковые параметры обзывать как название типа, `System.Type` в данном случае.
Это как https://www.fileformat.info/info/unicode/char/037e/index.htm и http://www.fileformat.info/info/unicode/char/3B/index.htm

2019-12-16 13:24 UTC, RawRCoder commented on TagsCloud/TagsCloudGenerator/Bases/WordsLayouterBase.cs
> +                RectangleF wordRectangle)>();
Скажи, тебе самому не страшно такое писать?)))

2019-12-16 13:24 UTC, RawRCoder commented on TagsCloud/TagsCloudGenerator/Bases/WordsLayouterBase.cs
> +        public Result<(string word, float maxFontSymbolWidth, string fontName, RectangleF wordRectangle)[]> ArrangeWords(
Серьёзно, тебе удобно это таскать? Не хочешь завести класс под это дело?

2019-12-16 13:24 UTC, RawRCoder commented on TagsCloud/TagsCloudGenerator/Bases/WordsLayouterBase.cs
> +        private readonly Func<(int freq, int maxFreq), int> getMaxSymbolSize;
Почему бы не завести `delegate`, мм?

2019-12-16 13:24 UTC, RawRCoder commented on TagsCloud/TagsCloudGenerator/Executors/PriorityExecutor.cs
> +        }
nit: Есть Aggregate:
```
        public Result<T> Execute(T input) 
            => executables.Aggregate(Result.Ok(input),
                (result, executable) => result.Then(executable.Execute));
```

2019-12-16 13:24 UTC, RawRCoder commented on TagsCloud/TagsCloudGenerator/Painters/PainterWithUserColors.cs
> +                        using (var font = new Font(fontName, maxFontSymbolWidth))
Здесь всё может развалиться. Например - мы не нашли fontName как шрифт

2019-12-16 13:24 UTC, RawRCoder commented on TagsCloud/TagsCloudGenerator/Painters/PainterWithUserColors.cs
> +                                new SolidBrush(colors[count = ++count % colors.Length]),
Достойно отдельной функции

2019-12-16 13:24 UTC, RawRCoder commented on TagsCloud/TagsCloudGenerator/PaintersAndSavers/PainterAndSaverWithUserImageSize.cs
> +                    using (var bitmap = new Bitmap(size.Width, size.Height))
Здесь тоже возможны исключения

2019-12-16 17:25 UTC, RGleb commented on TagsCloud/TagsCloudConsoleClient/EntryPoint.cs
> +            Console.WriteLine(new ParserOptionsHelp(container).GenerateHelp());
Тут проблема в том, что пользователь может не знать/забыть какие поддерживаются функции парсинга/сохранения/преобразования слов для облака и т.д. (если по коду, то какие поддерживаются фабрики). Поэтому я сделал такую справку (хотел ее к атрибуту в Help параметр прибить, но справка генерируется в рантайме и зависит от содержимого контейнера, еще пытался в рантайме взять атрибут и приписать в Help параметр нужную информацию, но оказалось, что объект атрибута судя по всему не синглтон :) )

2019-12-16 17:27 UTC, RGleb commented on TagsCloud/TagsCloudGenerator_Tests/SingletonScopeInstancesContainer.cs
> +        public Type Get<Type>() => container.Resolve<Type>();
Да, плохо сделал, исправлю

2019-12-16 17:29 UTC, RGleb commented on TagsCloud/TagsCloudGenerator/Bases/WordsLayouterBase.cs
> +                RectangleF wordRectangle)>();
На самом деле страшно это таскать по всему коду) Сделаю класс, как ты уже написал

2019-12-16 17:30 UTC, RGleb commented on TagsCloud/TagsCloudGenerator/Bases/WordsLayouterBase.cs
> +        private readonly Func<(int freq, int maxFreq), int> getMaxSymbolSize;
Чем он лучше в этой ситуации, чем Func?

2019-12-16 17:31 UTC, RGleb commented on TagsCloud/TagsCloudGenerator/Executors/PriorityExecutor.cs
> +        }
Проглядел, что можно через Aggregate, исправлю

2019-12-16 17:39 UTC, RGleb commented on TagsCloud/TagsCloudGenerator/Painters/PainterWithUserColors.cs
> +                        using (var font = new Font(fontName, maxFontSymbolWidth))
Пробовал подавать неправильные шрифты, он не падает, а заменяет их на `Microsoft Sans Serif`, но проверку на шрифт я делаю в классе `WordsLayouterBase`, наверное, стоит еще ее делать и в `PainterWithUserColors`, но тогда получится, что мы несколько раз проверяем шрифт, но с другой стороны эти классы независимы друг от друга и им надо каждому проверить шрифт. Думаю, что стоит дописать проверку и в `PainterWithUserColors`

2019-12-16 17:59 UTC, RGleb commented on TagsCloud/TagsCloudGenerator/PaintersAndSavers/PainterAndSaverWithUserImageSize.cs
> +                    using (var bitmap = new Bitmap(size.Width, size.Height))
Судя по всему у размеров `Bitmap` есть еще и верхняя граница) Допишу проверку

2019-12-16 18:10 UTC, RGleb commented on TagsCloud/TagsCloudConsoleClient/ParserOptions.cs
> +        public IEnumerable<string> Colors { get; set; }
Напишу `IReadOnlyList`, у него индексаторы есть)

2019-12-17 07:06 UTC, RGleb commented on TagsCloud/TagsCloudConsoleClient/ParserOptions.cs
> +        public IEnumerable<string> Colors { get; set; }
Возможно, ты имел в виду свойство `WidthAndHeight`, потому что только для него использовался `.ElementAt`, но у него я уже исправил на `IReadOnlyList` и индексаторы

2019-12-17 11:43 UTC, RawRCoder commented on TagsCloud/TagsCloudConsoleClient/EntryPoint.cs
> +            Console.WriteLine(new ParserOptionsHelp(container).GenerateHelp());
Ну ок

2019-12-17 11:48 UTC, RawRCoder commented on TagsCloud/TagsCloudGenerator/Bases/WordsLayouterBase.cs
> +        private readonly Func<(int freq, int maxFreq), int> getMaxSymbolSize;
Можно будет отказаться от совсем не нужного здесь тапла, сохранив при этом названия аргументов

2019-12-17 11:49 UTC, RawRCoder commented on TagsCloud/TagsCloudGenerator/Painters/PainterWithUserColors.cs
> +                        using (var font = new Font(fontName, maxFontSymbolWidth))
Да, уже выяснил, что оно нифига не падает) Не совсем обычно и ожиданно

2019-12-17 12:14 UTC, RawRCoder commented on TagsCloud/TagsCloudGenerator/Painters/PainterWithUserColors.cs
> +                                new SolidBrush(colors[count = ++count % colors.Length]),
nit: Жаль сразу не увидел. Вообще, по-человечески было бы наверное примерно так:
```
    public static class EnumeratorExtensions
    {        
        public static T CircularGetNext<T>(this IEnumerator<T> enumerator)
        {
            if (!enumerator.MoveNext())
            {
                enumerator.Reset();
                enumerator.MoveNext();
            }

            return enumerator.Current;
        }
    }

...

graphics.Clear(userColors.backgroundColor);
                    using (var colorsEnumerator = (userColors.colors as IEnumerable<Color>).GetEnumerator())
                    using (var solidBrush = new SolidBrush(Color.Black))
                        foreach (var word in layoutedWords)
                        {
                            solidBrush.Color = colorsEnumerator.CircularGetNext();
....
```

Каст там был бы не нужен, если бы colors был не массивом а IReadOnlyList или IEnumerable. Зато состояние у объекта пропадёт, а это - хорошо!

На твоё усмотрение

2020-10-17 22:55 UTC, closed without merging