Карпенко Давид
kontur-courses/fp pull request #43
Opened 2019-12-16 08:47 UTC by IAlmostDeveloper

@KartsevYaroslav

2019-12-17 17:28 UTC, KartsevYaroslav requested changes
Было бы круто если бы пользователю при некорректных введенных данных выводилось сообщение, а не эксепшн со стектрейсом

2019-12-17 17:28 UTC, KartsevYaroslav commented on ErrorHandling/Result_should.cs
>  using System;
у файла проблема с кодировкой, давай в UTF8 переделаем. Проверь все файлы из проекта ErrorHandling на верную кодировку

2019-12-17 17:28 UTC, KartsevYaroslav commented on ErrorHandling/Result_should.cs
> +using ErrorHandling;
Давай тесты все таки в отдельный проект вынесем

2019-12-17 17:28 UTC, KartsevYaroslav commented on ErrorHandling/Result.cs
> +            if (input.IsSuccess) return input;
можно упростить с помощью тернарного оператора

2019-12-17 17:28 UTC, KartsevYaroslav commented on TagCloud/CloudLayouter/CircularLayouter/CircularCloudLayouter.cs
> +            if (!IsCorrectSize(layouterSettings.ImageSize))
Будет круче, если унести валидацию настроек в саму модель настроек, таким образом если там будет много настроек, ты сможешь провалидировать сразу все и вывести понятное сообщение об ошибке.

2019-12-17 17:28 UTC, KartsevYaroslav commented on TagCloud/CloudLayouter/CircularLayouter/CircularCloudLayouter.cs
> +                    return Result.Fail<Rectangle>("Incorrect rectangle position");
Не хватает информации в сообщении об ошибке, не совсем понятно, что значит некорректная позиция

2019-12-17 17:28 UTC, KartsevYaroslav commented on TagCloud/CloudLayouter/CircularLayouter/CircularCloudLayouter.cs
> +            return Result.Fail<Rectangle>("Rectangle should be added after foreach block");
Не стоит писать в сообщении об ошибке информацию о внутренней логике. Внешний пользователь ничего не должен знать про `foreach block`

2019-12-17 17:28 UTC, KartsevYaroslav commented on TagCloud/CloudLayouter/CircularLayouter/CircularCloudLayouter.cs
> +            if (!IsCorrectSize(rectangleSize))
кажется достаточно проверки ниже о том, что прямоугольник не влез

2019-12-17 17:28 UTC, KartsevYaroslav commented on TagCloud/Visualization/CloudVisualization.cs
> +            var rectangleResult = layouter.PutNextRectangle(newRectangleSize);
здесь прям просится цепочка резалтов

2019-12-17 17:28 UTC, KartsevYaroslav commented on TagCloud/Visualization/CloudVisualization.cs
> +            paintRectangleOnCanvas = rectangleResult.Error.Equals("Incorrect rectangle position")
А почему Incorrect rectangle position это нормально? Ну и в любом случае не стоит завязывать логику на текст ошибки

2019-12-17 17:28 UTC, KartsevYaroslav commented on TagCloud/Visualization/CloudVisualization.cs
> +            if (CheckRectangleErrors(rectangleResult, out var paintRectangleOnCanvas)) return paintRectangleOnCanvas;
Кажется здесь тоже объединить в цепочку можно

2019-12-17 17:28 UTC, KartsevYaroslav commented on TagCloud/Visualization/CloudVisualization.cs
> +            foreach (var word in words.OrderByDescending(w => w.Value).Take(viewSettings.WordsCount))
Если написать еще один extension, который схлопывает множество резалтов в один, то этот код можно написать в fluent стиле

2019-12-17 17:28 UTC, KartsevYaroslav commented on TagCloud/Visualization/CloudVisualization.cs
> +            return Result.Ok<None>(null);
а зачем резалт, если всегда возвращается ок?

2019-12-17 17:28 UTC, KartsevYaroslav commented on TagCloud/Visualization/CloudVisualization.cs
> +            return Result.Ok<None>(null);
Здесь тоже зачем резалт при всегда успешном результате

2019-12-17 17:28 UTC, KartsevYaroslav commented on TagCloud/Visualization/CloudVisualization.cs
> +                result.OnFail(_ => throw new Exception(result.Error));
вместо выделения result в отдельную переменную, гораздо лучше продолжить цепочку

2019-12-17 17:28 UTC, KartsevYaroslav commented on ErrorHandling/Result.cs
> +            return input.Then(inp => OfAction(() => continuation(inp)));
а если придет неудачный резалт? Касается также метода выше

2019-12-18 07:25 UTC, IAlmostDeveloper commented on TagCloud/Visualization/CloudVisualization.cs
> +            return Result.Ok<None>(null);
тип возвращаемого значения не void, а Result<None> нужен для того, чтобы можно было применить складывание методов в цепочку с Then и OnFail

2019-12-18 07:26 UTC, IAlmostDeveloper commented on TagCloud/Visualization/CloudVisualization.cs
> +            return Result.Ok<None>(null);
цепочки методов, то же самое что и в случае выше

2019-12-18 07:42 UTC, IAlmostDeveloper commented on TagCloud/Visualization/CloudVisualization.cs
> +                result.OnFail(_ => throw new Exception(result.Error));
Понял

2019-12-18 07:57 UTC, KartsevYaroslav commented on TagCloud/Visualization/CloudVisualization.cs
> +            return Result.Ok<None>(null);
Изменять сигнатуру метода только ради цепочки не гуд. Резалт нужен только там, где у тебя метод может выполниться неудачно. В данном случае кажется достаточно сделать два первые метода void, а уже в зависимости от результата PaintAllWords принимать решение

2019-12-19 16:13 UTC, KartsevYaroslav requested changes

2019-12-19 16:13 UTC, KartsevYaroslav commented on TagCloud/Extensions/EnumerableExtension.cs
> +        public static Result<None> ToOneResult(this IEnumerable enumerable)
нужна более строгая типизация
IEnumerable => IEnumerable\<Result\<None\>\>

2019-12-19 16:13 UTC, KartsevYaroslav commented on TagCloud/Extensions/EnumerableExtension.cs
> +                        return Result.Fail<None>(result.Error);
по хорошему все уникальные ошибки надо сконкатенировать

2019-12-19 16:13 UTC, KartsevYaroslav commented on TagCloud/Visualization/CloudVisualization.cs
> +                if (!PaintAllWords(graphics).IsSuccess)
а здесь бы тебе как раз пригодился экстеншн SelectMany, который ты удалил
```
 return PaintAllWords(graphics)
                    .SelectMany(x => Result.Ok(bitmap))
                    .ReplaceError(x => x + "'Failed to visualize. Too many words.'");
```
Текст ошибки возможно даже не надо дополнять

2019-12-19 16:13 UTC, KartsevYaroslav commented on TagCloud/Visualization/CloudVisualization.cs
> +        private Result<Rectangle> TryPaintWordRectangle(Graphics graphics, Result<Rectangle> rectangleResult)
все будет работать и если вместо Result<Rectangle> в сигнатуре оставить просто Rectangle

2019-12-19 16:13 UTC, KartsevYaroslav commented on TagCloud/CloudLayouter/CircularLayouter/CircularCloudLayouter.cs
> +        public Result<Rectangle> PutNextRectangle(Size rectangleSize, out Size outRectSize)
а зачем тебе `out Size outRectSize`? У тебя же есть размер в возвращаемом прямоугольнике?

2019-12-19 16:13 UTC, KartsevYaroslav commented on TagCloud_Should/Tests/CircularCloudLayouter_Should.cs
> +//        [TestCase(-1, -1)]
с закоментированным кодом вряд ли примут ПР

2019-12-19 16:13 UTC, KartsevYaroslav commented on TagCloud/Visualization/CloudVisualization.cs
>          private void TryPaintWord(string word, int frequency, Graphics graphics, Result<Rectangle> rectangleResult,
здесь тоже достаточно просто Rectangle принимать

2019-12-19 16:13 UTC, KartsevYaroslav commented on TagCloud/Visualization/CloudVisualization.cs
> +            Size newRectangleSize)
newRectangleSize тоже не нужен, он же в Rectangle есть

2019-12-19 16:13 UTC, KartsevYaroslav commented on TagCloud/Visualization/CloudVisualization.cs
> +        private Result<Size> SetNewRectangleSize(int frequency, int wordLength)
Та же ошибка, которую обсуждали. Не стоит ради начала цепочки возвращать резалт. Достаточно как то так
```
            var size = SetNewRectangleSize(frequency, word.Length);
            return layouter.PutNextRectangle(size, out outRectSize)
                .Then(rect => TryPaintWordRectangle(graphics, rect))
                .Then(rect => TryPaintWord(word, frequency, graphics, rect, outRectSize));
```

2019-12-19 16:13 UTC, KartsevYaroslav commented on TagCloud/Visualization/ImageSettings.cs
> +            return !(rectangleSize.Width <= 0
двойное отрицание сложно читается, лучше заинвертить условие

2019-12-19 16:13 UTC, KartsevYaroslav commented on TagCloudForm/CloudPainter.cs
> +                .Then(_ => imageHolder.Image = cloudVisualization.Visualize().GetValueOrThrow())
если добавить еще одну строчку Then выше, то тебе не придется делать GetValueOrThrow()

2019-12-19 16:13 UTC, KartsevYaroslav commented on TagCloudForm/CloudPainter.cs
> +                .Then(_ => imageHolder.UpdateUi())
можно сделать еще один экстеншн, который принимает просто Action

2019-12-20 09:58 UTC, KartsevYaroslav requested changes

2019-12-20 09:58 UTC, KartsevYaroslav commented on TagCloud/Extensions/EnumerableExtension.cs
> +                if (element is Result<None> currentResult)
ненужная проверка, ты же запретил другие типы на уровне компиляции

2019-12-20 09:58 UTC, KartsevYaroslav commented on TagCloud/Extensions/EnumerableExtension.cs
> +                        if (isFirstFail)
как то слишком сложно.
```
            var uniqueErrors = new HashSet<string>();
            foreach (var result in results)
                if (!result.IsSuccess)
                    uniqueErrors.Add(result.Error);

            return uniqueErrors.Count == 0
                ? Result.Ok<None>(null)
                : Result.Fail<None>(string.Join(";", uniqueErrors));
```

2019-12-20 09:58 UTC, KartsevYaroslav commented on TagCloud/Visualization/ImageSettings.cs
> +        private bool IsNotCorrectSize(Size rectangleSize)
```
 private static bool IsCorrectSize(Size rectangleSize)
        {
            return rectangleSize.Width > 0 && rectangleSize.Height > 0;
        }
```
в коде есть еще один такой же метод

2019-12-20 09:58 UTC, KartsevYaroslav commented on TagCloud/Visualization/CloudVisualization.cs
> +        private void TryPaintWord(string word, int frequency, Graphics graphics, Result<Rectangle> rectangleResult)
не исправлено, все так же Result в параметрах

2019-12-22 08:20 UTC, KartsevYaroslav approved these changes

2020-10-17 22:53 UTC, closed without merging