Kazikulov Arzybek
kontur-courses/fp pull request #55
Opened 2019-12-18 14:43 UTC by Arzybek

@goodoldlameme

2019-12-19 05:44 UTC, goodoldlameme requested changes

2019-12-19 05:44 UTC, goodoldlameme commented on TagsCloudContainer/Layouter/Visualizer.cs
> +//        public static void Main(string[] args)
комментарии в коде

2019-12-19 05:44 UTC, goodoldlameme commented on TagsCloudContainer/DefaultWordsToSizesConverter.cs
> +                return Result.Fail<IEnumerable<(string, Size)>>(e.Message).RefineError(
а нельзя просто завернуть в `Result.Of()`

2019-12-19 05:44 UTC, goodoldlameme commented on TagsCloudContainer/DefaultWordsFilter.cs
> +            catch (Exception e)
тоже Result.Of

2019-12-19 16:43 UTC, Arzybek commented on TagsCloudContainer/Layouter/Visualizer.cs
> +//        public static void Main(string[] args)
Этот файл привязался еще с предыдущего задания, я его убрал из проекта, но случайно скопировал, вот он и не отобразился даже, удалил

2019-12-19 16:48 UTC, Arzybek commented on TagsCloudContainer/DefaultWordsToSizesConverter.cs
> +                return Result.Fail<IEnumerable<(string, Size)>>(e.Message).RefineError(
Done

2019-12-19 16:50 UTC, Arzybek commented on TagsCloudContainer/DefaultWordsFilter.cs
> +            catch (Exception e)
Done

2019-12-19 16:58 UTC, Arzybek commented
@goodoldlameme

2019-12-20 09:49 UTC, goodoldlameme requested changes

2019-12-20 09:49 UTC, goodoldlameme commented on TagsCloudContainer/DefaultWordsToSizesConverter.cs
> +                    var res = new List<(string, Size)>();
тут какой-то слишком объемный предикат получился, декомпозировать и вынести

2019-12-20 17:46 UTC, Arzybek commented on TagsCloudContainer/DefaultWordsToSizesConverter.cs
> +                    var res = new List<(string, Size)>();
Done

2019-12-20 17:46 UTC, Arzybek commented
@goodoldlameme

2019-12-21 09:25 UTC, goodoldlameme approved these changes

2020-10-17 22:53 UTC, closed without merging