Анисимов Андрей
kontur-courses/fp pull request #63
Opened 2019-12-20 05:21 UTC by GangBoss

@MaryaLoskutova

2019-12-20 16:52 UTC, MaryaLoskutova requested changes

2019-12-20 16:52 UTC, MaryaLoskutova commented on TagsCloudVisualization/ImageSaver/ImageSaverFactory.cs
> +            throw new ArgumentException($"Unexpected ImageExt {ext}");
тут не выполняется 1 пункт задания

2019-12-20 16:52 UTC, MaryaLoskutova commented on TagsCloudVisualization/ImageSaver/JpgSaver.cs
> +                var jpgEncoder = GetEncoder(ImageFormat.Jpeg);
это конечно не относится уже к этому заданию, но почему тут нельзя было сделать более расширяемый метод, чтобы по одному и тому же алгоритму просто разный формат сохранять?

2019-12-20 16:52 UTC, MaryaLoskutova commented on TagsCloudVisualization/PathHelper.cs
> +                        pathToResources = Directory.GetParent(pathToResources).FullName;
почему нельзя через Try проверить?

2019-12-20 16:52 UTC, MaryaLoskutova commented on TagsCloudVisualization/PathHelper.cs
> +                for (var i = 0; i < 3; i++)
а что это за шаманский цикл? ощущение, что у тебя тут странный способ получения пути ..\..\.. 
И сразу вопрос. А почему не положить файл в bin и не делать таких манипуляций?

2019-12-20 16:52 UTC, MaryaLoskutova commented on TagsCloudVisualization/Program.cs
> +            var container = ContainerProvider.Build();
необычный способ загружать настройки и потом уже резолвить контейнер)

2019-12-20 16:52 UTC, MaryaLoskutova commented on TagsCloudVisualization/Program.cs
> +            var saveResult = container.Resolve<IImageSaverFactory>().GetSaver(appSettings.ImageExt)
ты тут уже в ошибку свалишься, если ввести не тот сейвер, что ты поддерживаешь

2019-12-20 16:52 UTC, MaryaLoskutova commented on TagsCloudVisualization/Providers/Layouter/DrawableCloudLayouter.cs
> +            {
а зачем двойные скобки?

2019-12-20 16:52 UTC, MaryaLoskutova commented on TagsCloudVisualization/Providers/Layouter/Spirals/RectangleSpiral.cs
> +            var x = coefficient * spiralCounter;
зачем x, y, если одинаковые значения рассчитываются?

2019-12-20 16:52 UTC, MaryaLoskutova commented on TagsCloudVisualization/Providers/WordSource/TextSplitter.cs
> +            foreach (var line in lineSource)
тут можно на linq написать)

2019-12-20 16:52 UTC, MaryaLoskutova commented on TagsCloudVisualization/Providers/WordSource/WordSourceProvider.cs
> +                foreach (var changer in changerFactory.GetChangers(settings))
зачем каждый раз вызывать GetChangers? Он меняется от запроса к запросу?

2019-12-20 16:52 UTC, MaryaLoskutova commented on TagsCloudVisualization/Results/Result.cs
> +        public static Result<None> OfAction(Action f, string error = null)
точно все методы вызываются?

2019-12-20 16:52 UTC, MaryaLoskutova commented on TagsCloudVisualization/SettingsParser.cs
> +            var sizerType = Result.Of(() => (SizeSelectorType) Enum.Parse(typeof(SizeSelectorType), sizer));
если ты можешь обойтись tryParse, то лучше не надо дожидаться выброса exception

2019-12-20 16:52 UTC, MaryaLoskutova commented on TagsCloudVisualization/SettingsParser.cs
> +                return Result.Fail<ApplicationSettings>("cant parse imageExt");
can't

2019-12-20 16:52 UTC, MaryaLoskutova commented on TagsCloudVisualization/SettingsParser.cs
> +            if (!int.TryParse(maxObjectCount, out var count))
странно, что в остальных случаях ты даешь дефолтные значения, а есть не пришло максимальное число объектов - кидаешь ошибку

2019-12-20 20:05 UTC, GangBoss commented on TagsCloudVisualization/PathHelper.cs
> +                for (var i = 0; i < 3; i++)
Поменял на несколько менее шаманский так как этот путь используется чтобы получить доступ к файлам в которых лежат тексты

2019-12-20 20:07 UTC, GangBoss commented on TagsCloudVisualization/ImageSaver/ImageSaverFactory.cs
> +            throw new ArgumentException($"Unexpected ImageExt {ext}");
Исправил, так, как других сейверов нет, фабрика просто возвращает единственный, но решил её не удалять поскольку это кусочек предыдущего задания где требовалось оставить эти точки расширения

2019-12-20 20:09 UTC, GangBoss commented on TagsCloudVisualization/PathHelper.cs
> +                        pathToResources = Directory.GetParent(pathToResources).FullName;
Чем меньше кода в блоке try-тем очевиднее где может упасть ошибка, разве нет?

2019-12-20 20:10 UTC, GangBoss commented on TagsCloudVisualization/Program.cs
> +            var container = ContainerProvider.Build();
Настройки с контейнером никак не связаны. но да, порядок явно стоит поменять

2019-12-20 20:11 UTC, GangBoss commented on TagsCloudVisualization/Program.cs
> +            var saveResult = container.Resolve<IImageSaverFactory>().GetSaver(appSettings.ImageExt)
Аналогично: 
Исправил, так, как других сейверов нет, фабрика просто возвращает единственный, но решил её не удалять поскольку это кусочек предыдущего задания где требовалось оставить эти точки расширения

2019-12-20 20:12 UTC, GangBoss commented on TagsCloudVisualization/Providers/Layouter/DrawableCloudLayouter.cs
> +            {
Не представляю как они там оказались, явно подбросили

2019-12-20 20:15 UTC, GangBoss commented on TagsCloudVisualization/Providers/Layouter/Spirals/RectangleSpiral.cs
> +            var x = coefficient * spiralCounter;
удалили y

Но, подозреваю что x'у без у теперь скучно

2019-12-20 20:43 UTC, GangBoss commented on TagsCloudVisualization/SettingsParser.cs
> +            var sizerType = Result.Of(() => (SizeSelectorType) Enum.Parse(typeof(SizeSelectorType), sizer));
избавился

2019-12-20 20:43 UTC, GangBoss commented on TagsCloudVisualization/SettingsParser.cs
> +            if (!int.TryParse(maxObjectCount, out var count))
скорее всего были заданы значения ещё в дебагере, так-что в качестве параметров шли сломанные аргументы которые специально за этим передавались

2019-12-20 20:45 UTC, GangBoss commented on TagsCloudVisualization/SettingsParser.cs
> +                return Result.Fail<ApplicationSettings>("cant parse imageExt");
Да, это определенно был косяк...
![image](https://user-images.githubusercontent.com/49919388/71291149-937f9c80-2393-11ea-89a6-16327e776d41.png)

2019-12-20 20:47 UTC, GangBoss commented on TagsCloudVisualization/Results/Result.cs
> +        public static Result<None> OfAction(Action f, string error = null)
Удалил unused

2019-12-20 20:49 UTC, GangBoss commented on TagsCloudVisualization/Providers/WordSource/WordSourceProvider.cs
> +                foreach (var changer in changerFactory.GetChangers(settings))
Предполагается что в UI была бы возможность менять построение облака в рантайме, и задавать какие-то парметры changers

2019-12-20 20:51 UTC, GangBoss commented on TagsCloudVisualization/Providers/WordSource/TextSplitter.cs
> +            foreach (var line in lineSource)
Переписал

2019-12-20 20:54 UTC, GangBoss commented on TagsCloudVisualization/ImageSaver/JpgSaver.cs
> +                var jpgEncoder = GetEncoder(ImageFormat.Jpeg);
В консольной это требовало бы большего кол-ва параметров, а в UI предпологалось перезагружать облако при смене настроек, но в целом- имело смысл добавить такую функцию

2019-12-23 08:27 UTC, MaryaLoskutova approved these changes

2020-10-17 22:53 UTC, closed without merging