Солдатов Павел
kontur-courses/fp pull request #69
Opened 2019-12-22 20:06 UTC by Pasha0666

2019-12-22 20:07 UTC, Pasha0666 commented
@wasadus

2019-12-23 07:43 UTC, wasadus requested changes
Посмотрел, есть небольшие замечания.

2019-12-23 07:43 UTC, wasadus commented on TagsCloudContainer/TagsCloudConsoleVersion/Program.cs
> +namespace TagsCloudConsoleVersion
Попробуй добавить тестов, на правильную работу при ошибках.

2019-12-23 07:43 UTC, wasadus commented on TagsCloudContainer/TagsCloudConsoleVersion/Program.cs
> +            Parser.Default.ParseArguments<Options>(args).WithParsed(option =>
Стоит выделить в один или несколько методов то что внутри WithParsed, а то слишком длинно получается.

2019-12-23 07:43 UTC, wasadus commented on TagsCloudContainer/TagsCloudConsoleVersion/Program.cs
> +                if (!processor.IsSuccess)
Конструкция 
`                if (!result.IsSuccess)
                {
                    Console.WriteLine(result.Error);
                    return;
                }`
повторяется слишком часто, попробуй выделить её в метод/экстеншен класса Result, или использовать для этого методы OnFail или Then, если их хватит.
Ещё сейчас ты предполагаешь только консольный вывод ошибок. Может, оставить точку расширения, если, например, захочется дублировать ошибки в файл?

2019-12-23 07:43 UTC, wasadus commented on TagsCloudContainer/TagsCloudConsoleVersion/Program.cs
> +                var result = processor.GetValueOrThrow().Run(option.PathToFile, option.PathSaveFile,
Вроде здесь GetValueOrThrow и не нужен. После замены всех if`ов, скорее всего, будет видно, как лучше без этого написать.

2019-12-23 13:51 UTC, wasadus commented on TagsCloudContainer/TagsCloudConsoleVersion/Program.cs
> +namespace TagsCloudConsoleVersion
В смысле на правильные ошибки :)

2019-12-23 21:28 UTC, Pasha0666 commented
@wasadus

2019-12-24 05:29 UTC, wasadus approved these changes

2020-10-17 22:53 UTC, closed without merging