Заварзин Никита
kontur-courses/fp pull request #85
Opened 2020-12-13 18:59 UTC by Scindapsus345

@goodoldlameme

2020-12-15 09:47 UTC, goodoldlameme requested changes

2020-12-15 09:47 UTC, goodoldlameme commented on HomeExercise/hw_tc3/hw_tc3.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
солюшн внутри солюшна странно выглядит, можно было либо добавить проекты в этот солюшн либо рядом положить

2020-12-15 09:47 UTC, goodoldlameme commented on HomeExercise/hw_tc3/TagsCloudContainer/Program.cs
> +                .OnFail(err => throw new Exception(err))
Лучше залогировать ошибку, сохранить в creator не Value, а Result, а следом проверить, если в резалте, в который creater завернут нет ошибки, делать все остальное 
var creator = Configurator.GetContainer()
                .Then(cont => cont.BeginLifetimeScope())
                .Then(scope => scope.Resolve<TagsCloudCreator>())
                .OnFail(err => logger.LogDebug(err));
if (!creator.IsSuccess)
                return;
>

2020-12-15 09:47 UTC, goodoldlameme commented on HomeExercise/hw_tc3/TagsCloudContainer/Program.cs
> +                .OnFail(err => throw new Exception(err));
тут соответственно тоже лучше так не делать, логируем и просто завершаем программу
мы делали делали, чтобы везде сразу обработать ошибочные данные, а тут взяли и сделали по сути то же самое что было(уронили программу), да еще и исключение очень не конкретное кидаем

2020-12-15 09:47 UTC, goodoldlameme commented on HomeExercise/hw_tc3/TagsCloudContainer/TagsCloudCreator.cs
> +                "Шрифт с таким именем не найден в системе");
касается всех ошибок - стоит написать в тексте ошибки, какой именно шрифт, какой именно формат, какой именно размер и т.п. не подходят

2020-12-15 09:47 UTC, goodoldlameme commented on HomeExercise/hw_tc3/TagsCloudContainer/WordFilters/StopWordsFilter.cs
> +                typeof(StopWordsFilter).Name);
вместо такой конструкции можно написать nameof()

2020-12-15 09:47 UTC, goodoldlameme commented on HomeExercise/hw_tc3/TagsCloudContainer/CloudDrawer.cs
> +                        .RefineError("Возникла ошибка на слове " + word.Word);
лучше использовать интерполяцию $"Возникла ошибка на слове {word.Word}"

2020-12-15 09:47 UTC, goodoldlameme commented on HomeExercise/hw_tc3/TagsCloudContainer/CloudDrawer.cs
> +            ChangeImageSize(300);
сейчас вроде нигде не обрабатывается случай, когда облако не влезло на картинку заданного размера, тыкни пожалуйста если это не так

2020-12-16 10:36 UTC, goodoldlameme requested changes

2020-12-16 10:36 UTC, goodoldlameme commented on HomeExercise/.vs/VSWorkspaceState.json
> +  "ExpandedNodes": [
.vs папка должна быть в gitignore

2020-12-16 10:36 UTC, goodoldlameme commented on HomeExercise/hw_tc3/TagsCloudContainer/ImageSavers/ImageSaver.cs
> +            return Result.OfAction(() => bitmap.Save(path + "\\" + name + "." + FormatName, Format),
всегда лучше использовать интерполяцию вместо сложения строк

2020-12-16 10:36 UTC, goodoldlameme commented on HomeExercise/hw_tc3/TagsCloudContainer/ImageSavers/ImageSaver.cs
> +                "Не удалось сохранить файл с изобраджением");
опечатка

2020-12-16 10:36 UTC, goodoldlameme commented on HomeExercise/hw_tc3/TagsCloudContainer/Program.cs
> +                Console.ReadKey();
зачем?

2020-12-16 10:36 UTC, goodoldlameme commented on HomeExercise/hw_tc3/TagsCloudContainer/Program.cs
> +                Console.ReadKey();
уже все, ошибка произошла, завершаться и всё

2020-12-16 10:36 UTC, goodoldlameme commented on HomeExercise/hw_tc3/TagsCloudContainer/bin/Debug/Microsoft.Extensions.DependencyInjection.xml
> +﻿<?xml version="1.0" encoding="utf-8"?>
скопируй файл gitignore из корня проекта, который лежит в папке fp, bin папок тут тоже не должно быть

2020-12-16 13:26 UTC, goodoldlameme requested changes

2020-12-16 13:26 UTC, goodoldlameme commented on .gitignore
> +**/packages/*
телеграм упал, попробуем тут
все еще остались папки в репозитории, которые есть в гитигноре - packages и один какой-то файл из папки .vs, исправь, пожалуйста

2020-12-16 13:35 UTC, Scindapsus345 commented on .gitignore
> +**/packages/*
дело в том, что у меня в репозитории вообще ничего нет, только две папки fp и Homework. Ну и гитигнор соответственно

2020-12-16 13:35 UTC, Scindapsus345 commented on .gitignore
> +**/packages/*
Либо я что-то не понимаю)

2020-12-16 13:51 UTC, goodoldlameme commented on .gitignore
> +**/packages/*
Так оно внутри папки Homework, если ты сейчас в гит зайдешь в этот проект откроешь папку HomeWork, там будет видно эти папочки 
![image](https://user-images.githubusercontent.com/32187228/102356918-a42b1880-3fcf-11eb-9e0a-a4bc16a61e82.png)

2020-12-16 13:51 UTC, goodoldlameme commented on .gitignore
> +**/packages/*
вот .vs/hw_tc3/v16 и packages быть не должно

2020-12-16 13:51 UTC, goodoldlameme commented on .gitignore
> +**/packages/*
вот ссылка с которой скриншот https://github.com/Scindapsus345/fp/tree/master/HomeExercise/hw_tc3

2020-12-17 07:20 UTC, goodoldlameme approved these changes

2022-11-01 05:50 UTC, closed without merging