Шпора-2018 Белянин Андрей
kontur-courses/fp pull request #9
Opened 2018-12-16 19:28 UTC by Belianin

@Lyapa96

2018-12-17 13:25 UTC, Lyapa96 requested changes

2018-12-17 13:25 UTC, Lyapa96 commented on TagsCloudVisualization/TagsCloudVisualization/App/FileWorkers/ImageSaver.cs
> +                return Result.Ok(new FileSendResult());
Это не нужно, можно сразу
`return new FileSendResult()`

2018-12-17 13:25 UTC, Lyapa96 commented on TagsCloudVisualization/TagsCloudVisualization/App/FileWorkers/ImageSaver.cs
> +    public class FileSendResult
Зачем это?
В шарпе один файл - один класс

2018-12-17 13:25 UTC, Lyapa96 commented on TagsCloudVisualization/TagsCloudVisualization/App/Cloud/Image/Visualizer.cs
> +            return Result.Ok(image);
Здесь тоже не нужно, там автоматическая конвертация настроена.
И везде ниже тоже исправить нужно.

2018-12-17 13:25 UTC, Lyapa96 commented on TagsCloudVisualization/TagsCloudVisualizationTests/CircularCloudLayouterTests.cs
> +            countedWords = counter.Count(false, rawString.ToString());
У тебя комплится эта штука?
Склонируй в чистую папку

2018-12-17 13:25 UTC, Lyapa96 commented on TagsCloudVisualization/TagsCloudVisualization/Program.cs
> +            var container = builder.Build();
Давай вынесем метод, который конфигурирует и возвращает контейнер. Чтобы не засорять Main

2018-12-17 13:25 UTC, Lyapa96 commented on TagsCloudVisualization/TagsCloudVisualization/Program.cs
> +            runner.Run(args);
Хочется чтобы у тебя программа полностью была функциональной, даже отсюда возвращался бы Result и в случае ошибки выводил бы в консоль, или `throw` произошедшая ошибка

2018-12-19 04:24 UTC, Lyapa96 requested changes

2018-12-19 04:24 UTC, Lyapa96 commented on TagsCloudVisualization/TagsCloudVisualization/Program.cs
> +            return builder
Давай метод назовем ConfigureBuilder - у него будет одна обязанность сконфигурировать.
А дальше в Main сделаем Build и затем Resolve

2018-12-19 04:24 UTC, Lyapa96 commented on TagsCloudVisualization/TagsCloudVisualization/Program.cs
> +                GetRunner().Run(args);
Тут нужно без try catch => Run тоже возвращает `Result`

2018-12-19 04:24 UTC, Lyapa96 commented on TagsCloudVisualization/TagsCloudVisualization/Program.cs
> +                GetRunner().Run(args);
И там уже OnFail и поехали

2018-12-19 04:24 UTC, Lyapa96 commented on TagsCloudVisualization/TagsCloudVisualization/App/FileWorkers/FileSaveResult.cs
> +    public class FileSaveResult
А какое отличие от `None`?

2018-12-19 04:24 UTC, Lyapa96 commented on TagsCloudVisualization/TagsCloudVisualization/App/ConsoleApplication.cs
> +            return Result.Ok(ParseArguments(args))
В целом норм)

2018-12-19 17:56 UTC, Belianin commented on TagsCloudVisualization/TagsCloudVisualization/App/FileWorkers/FileSaveResult.cs
> +    public class FileSaveResult
Да, вообщем-то действительно разницы нет. Делал скорее просто на будущее, но наверное мне оно и не понадобится.

2020-10-17 22:55 UTC, closed without merging